---
title: nextcloud
---

An secure nextcloud instance has been set up on a DigitalOcean VPS, where all our research materials reside. This allows controlled remote access to communal sets of files, organized according to a consistent and controlled directory structure.

## Directory structure {#directory_structure}

The file server has the following structure:

` /NextCloud`\
` ../universal`\
` ..../ADS`\
` ..../PKAP`\
` ..../WARP`\
` ../admin`\
` ..../transcripts`\
` ../your-name`\
` ..../MaxQDA-external`\
` ..../MaxQDA-backups`

`/universal` contains the media that we will work with. This media has been edited so that it is more amenable for our work (i.e. cleaned audio, concatenated videos, manageable file sizes, systematically-named files, etc). Use these files when you import media into MaxQDA.

`/admin` contains sensitive data, finalized transcripts and raw, unedited media copied directly from the recording devices.

`/your-name` contains your own working environment. Set your MaxQDA external files directory to point to `/your-name/MaxQDA-external-files/`. Set your MaxQDA automated backups directory to the `/your-name/MaxQDA-backups/`.

When contributors are finished working with a MaxQDA file, they will place it it in `/your-name` and append the date and version number to the file name (i.e.: `PKAPJune5-x121219-1.mx18`). Having a file named in that way located in the `/your-name` directory will signal to the admin that this file is ready to be merged into a unified MaxQDA file.

After the admin merges the file, he/she will move it to `/your-name/old-exports` for future reference and copy the merged file (without date and version number in the filename) to `/your-name`. Contributors should only work with such files that are fully up to date or that they have created from scratch in the case of transcription work.

## Accessing the Nextcloud {#accessing_the_nextcloud}

### Using a web browser {#using_a_web_browser}

Go to nextcloud.e-curators.org and input your username and password.

If you do not yet have an account, ask the admin to set one up for you. Remember to change the password the admin provides after logging in for the first time.

### Using a desktop client or tablet/smartphone app {#using_a_desktop_client_or_tabletsmartphone_app}

Download the Nextcloud client for your operating system at <https://nextcloud.com/install/#install-clients>.

The installation wizard takes you step-by-step through configuration options and account setup. First you need to enter the URL of our Nextcloud server: <https://nextcloud.e-curators.org>

After pressing next you will be prompted to enter your username and password.

The next screen allows you to select which folders to sync. You may want to limit which folders to sync if you have limited space on your computer\'s hard drive. At the very least, please ensure that you sync the your own working folder (`/your-name`) and `/universal`. Also select the folder on your computer where you want Nextcloud will sync (choose the default directory to keep things simple). This step is not included when setting up the smartphone or tablet apps.

When you have completed selecting your sync folders, click the Connect button at the bottom right. The client will attempt to connect to your Nextcloud server. It will also start synchronizing your files.

The desktop client can be finicky. Please ensure that all files have finished syncing before making further changes.

See the [official Nextcloud documentation](https://docs.nextcloud.com/desktop/2.6/installing.html) for more information.

## Syncing content {#syncing_content}

### How to set up cloud-synced folders: {#how_to_set_up_cloud_synced_folders}

1.  Download the Nextcloud desktop client from <https://nextcloud.com/clients/>.
2.  In the \'host\' field, include `nextcloud.e-curators.org`, and use your login credentials provided by the admin to sign in.
3.  Select which folders you would like to sync. This selection must include the `/universal` folder and the folder named for you (`/your-name`).

### Then configure MaxQDA: {#then_configure_maxqda}

1.  In the MaxQDA Preferences (MacOS) or Settings (Windows), identify `/universal` as the folder where MAXQDA should look when opening externally stored files.
2.  Ensure that each individual document points to the correct file by checking the document properties menu, which can be accessed by right clicking on a document and selecting \'Properties\' from the bottom of the menu.

### Accessing external files {#accessing_external_files}

MaxQDA does not change the external files. It just assigns timestamps or \'line-stamps\' to codings that correspond with various parts of the file being coded.

MaxQDA only supports absolute paths (and not relative paths) when identifying external files and folders, so the location of this folder will be unique to your own computer (i.e. `/Volumes/zackbatist/Nextcloud/universal` and `/C:/Users/costis/NextCloud/universal` each sync with the same cloud storage).
