---
title: Information systems and organizational structures
---

Information systems are used to draw together the work that occurs in various settings, at various times and tempos, by various people, who implement various tools, methods and approaches that produce heterogenous yet complementary sets of information. Specifically, they facilitate systematic recording, organization, storage, retrieval, synthesis and comprehension of distributed sets of information.
The selective, strategic or subconscious implementation of or engagement with components of information systems elicit underlying commitments and normative expectations held by the individuals, communities and interests that they serve [@lucas2012; @huggett2012b; @huggett2017].

Information infrastructures are information system designs that carry particular intentions and use cases in mind.
It is necessary to imagine how a system will potentially be used prior to constructing it, but its implemented may deviate from these expectations.

Organizational structures refer to the commonly accepted and enforceable set of administrative relationships that are established to conduct work in an organized and legitimate manner.
May be evaluated in terms of intersections between domains, role and degrees of understanding.

**Domains** are assemblages of knowledge, materials, tools or experiences that are associated with the people who wield them.
Groups of people who share similar associations may constitute specialist research communities.
Belonging to a research community entails adherence to and reproduction of established legitimate practices, language and sensibilities, which emerge out of the circumstantial constraints to produce legitimate knowledge using the particular kinds of knowledge, materials, tools and experiences that distinguish the domain as a distinct field of practice.
Association with a domain also entails embodied experiences that are somewhat tangential to the actual practices that characterize the domain. Membership is expressed by adorning symbols, wearing certain styles of clothing, using certain styles of language and means of communication, association with certain domain-specific tools or objects in social or non-work contexts, or participation in shared memory or nostalgia.
The expectation to perform membership in these ways has implications regarding the domains' openness to diversity, since certain expressions used to signify belonging may be strongly associated with broader societal norms pertaining to particular subsets of the population, and those individuals would be able to enact these behaviours more easily or in ways that are deemed more genuine.

**Roles** are administrative titles associated with particular sets of duties, responsibilities or privileges.
Relationships between roles are typically characterized as power-imbalances.

**Degrees of understanding** refer to a person's relative ability to act in accordance with the tenets of a particular domain.
A **novice** is someone who lacks the intuitive understanding and practical ability to act that experts possess. Expertise accrues through experience as novices carry out tasks, which allows them to consider how operations lead to broader outcomes and have implications for the successful implementation of activities.
An **expert** is someone who intuitively understands the limits and possibilities of one's approach, who is aware of typical pragmatic constraints that may get in the way, and who is capable of carrying out actions to attain a goal with confidence and methodological rigour.

# Related concepts
**Intuition / intuitive** refers to the ability to immediately understand a situation and what needs to be done in order to implement a task.
Typically associated with *expert* or those with *intermediate* knowledge or experience.
Arises from past experiences, especially experience where all stages of the task were completed, and where the value of the task was made clear.
Also manifested by or associated with the ability to translate (though not necessarily articulate) between abstract procedures and direct practical experiences.
