---
title: Collaborative workflows using MaxQDA
---

MaxQDA project files (.mx18) should only be worked on locally, by one user at a time. There is major risk of database corruption if the same file is being worked on my multiple users on different computers, as assisted by Dropbox sync, for instance.

We will therefore collaborate by merging independently-worked MaxQDA files on a task-by-task basis. See [Merging MaxQDA project files](Merging_MaxQDA_project_files "wikilink") for further details.

One administrative user (admin) will be responsible for managing these merges. This requires that tasks be carefully allocated and that all contributors communicate effectively about the work that needs to be done.

The merge admin will be responsible for synchronizing the shared file server containing the most up to date merged file, archiving outdated drafts, and ensuring that all contributors\' work occurs in a seamless manner. See [Nextcloud](Nextcloud "wikilink") for more details.

A few different kinds of work warrant different workflows:

-   Transcription
-   Initiating new coding
-   Continuing existing coding

## Transcription

*For transcription notation guidelines, see [Transcription](Transcription "wikilink").*

When transcribing an audio/visual document to a text-based format using MaxQDA\'s built-in transcription tools, each transcript should be produced as its own .mx18 project file. Each file will eventually be merged into a unified .mx18 project file containing all available transcripts.

1.  Create a new MaxQDA project. Name it according to the following scheme: `InterviewerName-YYYYMMDD.mx18` or `BrandonOlson-20190606.mx18`.
2.  Import the media to be transcribed as a new document. MaxQDA will make a copy of this file in the predefined External Files directory (which should be pointed at `/your-name/MaxQDA-external`, which is paired with a .dat file containing crucial metadata.
3.  Once you complete your transcription, contact the admin to notify him that the transcript is ready to be merged into a unified project file.
4.  After completing the merge, the admin will then move the dedicated .mx18 file to an archive folder in the `/admin` directory and an updated unified file will be made available to all users.

## Working with existing project files

When tasked with coding or memoing work, you will likely be working with merged .mx18 files.

1.  Prior to the initiation of such work, the admin will create copies of the unified and most up to date .mx18 file, personalize them with each user\'s name, and place them in each user\'s working directory.
2.  Users will then work with their personalized file exclusively.
3.  When users have completed their tasks, they will contact the admin to notify him that the work is ready to be merged into a unified project file. Users should refrain from making future changes to their personalized .mx18 file after they notify the admin about the completion of their task.
4.  After completing the merge, the admin will then move each personalized .mx18 into an archive folder in the `admin` directory and an updated unified file will be made available to all users.

## Other things

### Backups and archives

In the MaxQDA preferences or settings menu, change the folder where backup files are saved to the `/your-name/MaxQDA-backups` subfolder.

Ensure that backsups are made automatically and on a regular basis by selecting these options in the preferences menu.

When you load a .mx18 file you will be prompted to save a backup if you have not done so in a preset number of days (as specified in the backup preferences). Each backup will be timestamped, but the naming scheme can\'t be changed to include the user's name (hence why we have different backup folders for each contributor).

It is also possible to save backups manually by selecting \'Save Project As\' from the File menu.

### User management

MaxQDA enables rudimentary user management settings. This is meant to help keep track of who makes what changes or codings, and allows us to compare how we code things in different ways so that we can potentially mitigate bias.

After every merge, select \'change user\' from the \'teamwork\' setting on the \'home\' ribbon (icon is a human silhouette), select your username from the dropdown and enter your password.
