---
title:  Cul3 overexpression depletes Nrf2 in breast cancer and is associated with sensitivity to carcinogens, to oxidative stress, and to chemotherapy
author: 
  - name: Martin Loignon
  - name: Weimin Miao
  - name: Lianggao Hu
  - name: Andrew Bier
  - name: Tarek A. Bismar
  - name: P. James Scrivens
  - name: Koren Mann
  - name: Mark Basik
  - name: Amélie Bouchard
  - name: Pierre O. Fiset
  - name: Zachary Batist
    orcid: 0000-0003-0435-508X
  - name: Gerald Batist
date: 2009-07-28
# description: ""
subtitle: |
  Molecular Cancer Therapeutics --- 
  <a class="link me-1" href="https://doi.org/10.1158/1535-7163.MCT-08-1186" target="_blank_" rel="external">10.1158/1535-7163.MCT-08-1186</a>
---
## Abstract
Nrf2 is the key transcription factor for cytoprotective gene programs. Nrf2 is normally maintained at very low concentrations by proteasomal degradation, through its interaction with the adapter protein Keap1 and the Cul3 E3 ligase. Increased Nrf2 concentration resulting from loss of function Keap1 mutations has been described in chemoresistant non–small cell lung cancer. Previous studies in breast cancer showed low levels of some Nrf2-regulated detoxification genes, but the mechanism has not been systematically examined. We found that half of the breast cancer cell lines examined have decreased concentration of Nrf2 compared with normal mammary epithelial cell lines, associated with variable but detectable levels in Keap1 levels, and consistently increased Cul3 mRNA and protein. Immunochemistry showed that 7 of 10 breast cancer specimens examined also have low Nrf2 levels and increased Cul3. Keap1 protein levels are variable. We found no C23Y mutation in Keap1 of any of the cell lines. Using siRNA, we silenced Cul3 in MCF-7 breast cancer cells, and microarray analysis reveals the induction of GCL, NQO1, AKR1C1, UGDH, and TXN by at least 2-fold. The Nrf2-regulated ABCC1 drug transporter was also found to be increased. These Cul3-silenced MCF7 cells are highly resistant to oxidative stress induced by H2O2, to the carcinogen benzo(a)pyrene, and to both Doxorubicin and Paclitaxel. This high Cul3/low Nrf2 signature may be key to cellular sensitivity to both chemical carcinogeneic stimuli as well as to cytotoxicity of commonly used chemotherapeutic drugs in established breast cancers. [Mol Cancer Ther 2009;8(8):2432–40]

---

::: {.callout-note collapse=true icon=false}
## {{< fa code >}} BibTeX

```BibTeX
@article{loignon2009,
title = {Cul3 Overexpression Depletes Nrf2 in Breast Cancer and Is Associated with Sensitivity to Carcinogens, to Oxidative Stress, and to Chemotherapy},
author = {Loignon, Martin and Miao, Weimin and Hu, Lianggao and Bier, Andrew and Bismar, Tarek A. and Scrivens, P. James and Mann, Koren and Basik, Mark and Bouchard, Amélie and Fiset, Pierre O. and Batist, Zachary and Batist, Gerald},
date = {2009-08-01},
journaltitle = {Molecular Cancer Therapeutics},
volume = {8},
number = {8},
eprint = {19638449},
eprinttype = {pmid},
pages = {2432--2440},
issn = {1535-7163, 1538-8514},
doi = {10.1158/1535-7163.MCT-08-1186},
url = {http://mct.aacrjournals.org/content/8/8/2432},
abstract = {Nrf2 is the key transcription factor for cytoprotective gene programs. Nrf2 is normally maintained at very low concentrations by proteasomal degradation, through its interaction with the adapter protein Keap1 and the Cul3 E3 ligase. Increased Nrf2 concentration resulting from loss of function Keap1 mutations has been described in chemoresistant non–small cell lung cancer. Previous studies in breast cancer showed low levels of some Nrf2-regulated detoxification genes, but the mechanism has not been systematically examined. We found that half of the breast cancer cell lines examined have decreased concentration of Nrf2 compared with normal mammary epithelial cell lines, associated with variable but detectable levels in Keap1 levels, and consistently increased Cul3 mRNA and protein. Immunochemistry showed that 7 of 10 breast cancer specimens examined also have low Nrf2 levels and increased Cul3. Keap1 protein levels are variable. We found no C23Y mutation in Keap1 of any of the cell lines. Using siRNA, we silenced Cul3 in MCF-7 breast cancer cells, and microarray analysis reveals the induction of GCL, NQO1, AKR1C1, UGDH, and TXN by at least 2-fold. The Nrf2-regulated ABCC1 drug transporter was also found to be increased. These Cul3-silenced MCF7 cells are highly resistant to oxidative stress induced by H2O2, to the carcinogen benzo(a)pyrene, and to both Doxorubicin and Paclitaxel. This high Cul3/low Nrf2 signature may be key to cellular sensitivity to both chemical carcinogeneic stimuli as well as to cytotoxicity of commonly used chemotherapeutic drugs in established breast cancers. [Mol Cancer Ther 2009;8(8):2432–40]},
langid = {english},
}
```
:::