---
title: Information system
permalink: /Information_system/
---

Information systems are used to draw together the work that occurs in various settings, at various times and tempos, by various people, who implement various tools, methods and approaches that produce heterogenous yet complementary sets of information. Specifically, they facilitate systematic recording, organization, storage, retrieval, synthesis and comprehension of distributed sets of information. The selective, strategic or subconscious implementation of or engagement with components of information systems elicit underlying commitments and normative expectations held by the individuals, communities and interests that they serve [@lucas2012; @huggett2012b; @huggett2017].

## Infrastructures

Information infrastructures are information system designs that carry particular intentions and use cases in mind. It is necessary to imagine how a system will potentially be used prior to constructing it, but its implemented may deviate from these expectations.

## Components of archaeological information systems

Information systems may comprise of tangible and intangible carriers of information.

- tags
- labels
- ephemeral scrap notes
- journal entries
- memory cards
- shell scripts
- outdated theolodite hardware drivers
- stories / jokes (repeated as warnings or to convey (im)proper practices)

