---
title: Actor-Network Theory
alias: https://wiki.zackbatist.info/index.php/Actor-network_theory
---
Actor-network theory (ANT) posits that all things that comprise the world are co-created through their relations with other things.
Non-human objects not only frame how human beings inhabit the world, but "push back" upon human actions with significant effects.
"a disparate family of material-semiotic tools, sensibilities and methods of analysis that treat everything in the social and natural worlds as a continuously generated effect of the webs of relations within which they are located. It assumes that nothing has reality or form outside the enactment of those relations.
Its studies explore and characterise the webs and the practices that carry them" [@law2008: 141].

## In SSK
ANT was used to better understand the physical and communicative mechanisms --- which are made up of non-human agents and information objects --- that scientists relied upon to capture, document and ascribe meaning to particular facets of the world.
ANT posits that scientists can only identify, characterize and understand objects of interest by co-creating their conceptions of reality alongside non-human agents.
Latour and Woolgar stated that science is primarily concerned with the creation of an ordered account of reality, rather than the transfer of information pertaining to the world into human-understandable formats.
They characterize the latter of these two propositions as the practices enacted in order to fulfill the former aim.
However, from a pragmatic perspective, these two processes may be rendered as intertwined and inseparable threads of a unified experience of knowledge production [@latour1986: 245].

## Example
the photographic outputs of a bioassay, which was a predominant object of discussion in their work, determines and represents the existence and qualities of discrete proteins that have been extracted from cell samples through reactions with specially selected reagents, marked with dyes selected for their non-reactive qualities, and pulled through a filtration medium that separates proteins according to their mass, molecular structure, and electromagnetic properties.
A large number of material entities are thus selected and mobilized due to the researcher’s understanding that such an assemblage might contribute to the representation of a targeted set of phenomena.
More specifically, certain reagents are added to cell samples that bind with proteins that constitute cell walls, allowing for inner proteins to be extracted.
Other reagents that only bind to particular targeted proteins and that have been engineered to have certain identifiable physical and electromagnetic properties impart these qualities onto the now merged molecule composed of both targeted protein and reagent. Dyes that complement the design of the reagent and of the overall bioassay protocol are bound to these molecules, rendering them visible to the human eye.
Molecules are then pulled through a conductive gel whose own material characteristics and density allow for only electrically charged molecules to be pulled through, given the placement of a polar-opposite charge at the far end of the gel.
Once movement of the proteins have settled, (caused, in part, by the gradual solidification of the gel that inhibits further movement) the entire gel is photographed and the relative positions of dyed molecules are marked to denote their discrete existence and other relevant qualities rendered through association with their respective reagents.
Knowledge is thus obtained by humans through the selective assembly of various material actors, whose interactions are already understood and deemed reliable, in order to render an account of reality based upon their projected experiences.
