---
title: Activity theory
alias: https://wiki.zackbatist.info/index.php/Activity_theory
nocite: |
  @engestrom2000
---

Examines the systematically-organized series of relations that comprise activities.
Activities are understood as the relations between human subjects and the physical or conceptual tools or environments with or within which they act, and the motives or objectives that drive the system forward in a particular direction [@leontev1974: 22-23].
Activity theory is useful to examine how people mobilize a series of physical and conceptual tools to overcome the conditions that separate actors' current states from their desired goals.
In this sense, activity theory prioritizes the situated perspectives and experiences of human subjects while still trying to account for the agency that tools exhibit in their experiences as components of activity systems delegated towards addressing particular tasks.
More specifically, activity theory helps to draw generalized accounts of practices employed in research projects.
Documenting taken-for-granted aspects of work in a structured manner provides a unique window into how such practices contribute to broader disciplinary norms or professional mindsets.
Recorded conversations and observations of enacted practices may be compared to determine how goals and strategies for achieving them are drawn up with the actual implementation of tasks.
This contributes to understanding how certain challenges are perceived by involved stakeholders, how contingencies are accounted for, and how indicators of success may change as work progresses.
Using activity theory effectively is not about describing the minute processes of enacted work, but rather about investigating how tasks and operations are strategically implemented as part of a coordinated effort to achieve broader goals.
