---
title: Determining a Plan of Action
date: 2011-09-22
categories:
  - plan of action
draft: true
---

So today I met with Dr. Graham and we decided on different methodologies I can use for my project.
In order to examine the relationship between wine and social structure in the Bronze Age Aegean, I'm going to be using network analysis to trace the flow of commodities (notably wine, grapes and other related products) throughout the region.
I'm also going to look at drinking vessels, analyzing the vessel types, their origins, and the residues that may have been left behind.
I will also include a look at Homeric feasting scenes.

It's good that I now have a clear goal of what data I need to attain, and how to do it.
It really looks like this project is shaping together at last.
But I still have to go one step at a time.
I have to start by defining some basic assumptions about my topic in order to understand the context that I will be writing about.
So for next week I'm going to try to determine how the governing body of the Mycenaean citadels functioned, and whether it was loosely composed of a "nexus of social relationships", as Dr. Graham put it, or if it has a more concrete structure.
I'll post my thoughts on that once I have it finished.
