---
title: Road Trip Through Arizona
date: 2011-12-30
categories:
  - Travel
  - Arizona
  - Sedona
  - grad school
  - road trip
draft: true
---

Much has happened since my last blog post.
We've been on the road a lot, travelling through Arizona.
After we left San Diego, we arrived at Scottsdale, where we stayed just for the night.
It's kind of a bland city, and it was just a stopover on our way to Sedona.

Sedona has some really amazing scenery, being right in the middle of "red rock country".
We arrived after sunset so we couldn't do anything exciting, but today we rented a jeep and went on the trails.
I got a bunch of great photos of the mountains, although we didn't see any animals at all.
Now we're at the Grand Canyon, where we will go on a mule ride partway down the gorge.

I also got a lot done for my grad applications.
I sent in all of my letters of intent, and I started contacting potential supervisors.
In many of these small towns there is not much to do at night so it's good to be productive.
It's amazing how much can get done when you are across the continent from home.
