---
title: Presenting at the Colloquium on Digital History and the Transnational History of Nursing
date: 2012-03-22
categories:
  - here comes the sun
  - summer
draft: true
---

The school year is winding down and the weather in Ottawa is gorgeous.
You would think that it would be getting kind of hard to concentrate, but in fact I am going at a much better pace these past few weeks.
I feel a lot more motivated, and I even get a lot of work done outside, which is a nice change of scenery (pardon the pun).

Aside from the assignments for my other classes, my Honours Project is going quite smoothly.
Tomorrow I will be presenting at the [Colloquium on Digital History and the Transnational History of Nursing](http://www2.carleton.ca/history/events/transnational-history-three-public-events/), along with Dr. Graha, Peter Holdsworth, and distinguished professor Pierre-Yves Saunier, visiting from France.
I will be explaining how I used network analysis in my project, and also on how this methodology can be used in archaeology or other academic disciplines of the social sciences.
I had the opportunity to meet with Dr. Saunier yesterday, and it seems that our research interests are quite common, even though they deal with different topics in separate settings of time and space.

I still have to make some revisions of my slides and presentation notes, but I will post these after the talk.
This will be my first academic presentation, and I really hope that it goes smoothly so that I can keep this productive momentum that I have garnered these past few weeks.
