---
title: General Update
date: 2012-01-22
categories:
  - data entry
  - writing
draft: true
---

I do realize that I've been neglecting this blog since the start of the winter break, and I must get back to posting updates and thoughts concerning my honours project.
Since the new semester started I've been working on more data entry, working with books obtained through Carleton's interlibrary loan office.
Many of the books that I request are delivered to Ottawa a few days later, so hopefully I will be able to finish all of the basic data entry by my deadline this Thursday.
However, some of the excavation reports are either in Greek, German or Italian, and it would be great if someone who knows these languages can help garner an understanding of the specific terms that I need to know.

Starting next week, once all of the data is collected and organized properly, I will start writing.
Admittedly I haven't been writing as much as I should be, even just small thoughts.
The absence of recent posts on my blog is evidence of this.
Of course I have been keeping track of aspects of the excavation reports which I am using, but no penetrating thoughts have been developed during the past few weeks.
Only notes and general ideas of the original authors have been taken down, but these can be used when I actually get into writing mode in the next little while.
