---
title: "Writing the Field - Blog #1"
date: 2013-01-20
categories:
  - Writing the Field
  - academic writing
  - the zone
draft: true
---

In order to improve upon my writing abilities, it is first necessary to recognize the workflows that I tend to follow.
This blog post is meant to be a reflection of my current writing processes, noting the conditions that enable me to write best, and also the factors that slow me down and cause writers block.

I'm going to start off on a positive note.
What are the conditions that enable me to write well, get on a roll, and hammer down ideas like It's nobody's business? First of all, I like writing in a busy environment.
I like working in coffee shops, atriums, lobbies, libraries or even household kitchens or living rooms.
However, I prefer to be by myself at the same time.
I know this seems contradictory, but I must be isolated within a crowd in order to do my best writing, like sitting alone in a coffee shop for instance.
If I am forced to write at a desk in my room, away from hustle and bustle, I tend to play some [ambient instrumental music](http://8tracks.com/lemonlimepie/quiet-nights-space-flights), which gets me into a rhythm.
This helps the ideas flow onto a page, and allows me to skip over a troubled sentence, preserving the rhythm that the song provides for me.
I can go for hours like this without leaving my desk, and if I get up to get some water or do some other mundane task, this 'roll' will probably be over when I get back.

I find that when I write productively I enter a certain mindset that breaks very easily.
Before I start I try to conclude my prior thoughts, perhaps by finishing up my leisurely online reading list or sending off an email that I've been contemplating about.
But this can backfire, I can find an article that links me to a chain of other articles, or I could get side-tracked into dealing with whatever the email is about.

I also try to make sure that everything I need is within arms reach.
I close every non-relevant program on my computer, I open the most important sources on my PDF reader/browser (I find that reading PDFs in Chrome is best), and I clear my desk so only essential things are right next to me.
I have a pretty broad desk that allows me to spread out, but some coffee shops have very small tables that don't permit you to stretch out.

After reflecting on my writing habits, it seems that I work in two stages.
First I try to get my main ideas onto paper (or rather a word processor) in a cohesive and comprehensive way.
I find that once these ideas are down, which is often the main challenge for me, supplementary work is much easier.
This would consist of reorganizing and smoothing out paragraphs, transitioning ideas, linking back to the thesis, or adding examples or analogies to illustrate a point.
I sometimes get side-tracked when doing this.
I could get carried away with a certain side-point that I try to emphasize too much, or I could be looking for an example from previous work on the topic when I stumble across another somewhat relevant article that takes me in a different direction.
I often have to remind myself that I have a paper to write, and that I have to continue on the course that I laid out.
So the 'roll', the uninterruptible mindset that enables me to get a paper finished, could be applied to both of these stages of writing.

If there's one way to characterize my writing process, It's this: once I'm in 'the zone' I tend to be very productive.
It's getting there, and staying there, that is the main challenge for me.

#### Comments
**K-Bish:**
I completely agree with you about needing to be in the zone or "on a roll", as well as needing background noises.
I think that by being in a group of other people doing their own thing I'm forced to be more focused on things and less distracted; I'm at that coffee shop for a reason and cannot leave until it's accomplished!
But if I'm with other people at the table, their actions will distract me, or they will interrupt me in a way that dissolves that 'roll'.
Do you feel that you have to be in the zone to do any editing as well? I find sometimes that I need to edit in chunks, and that I cannot be in a busy environment when I'm editing.

**Zack:**
The main challenge for me is getting my main thoughts on paper, and then I go through the process linking them all together.
Once it's all there, reviewing it is much easier for me. I go through each recognizable portion of my paper, then a full run-down to see if the revised version could be read naturally by my expected audience.
After this I tend to take a long break (usually a day) in order to review it later with fresher eyes.

**Matthew:**
Zack, I know exactly what you mean when on a 'roll' is interrupted by a glass of water, or food, or something interesting on the internet, or, 'stare at the wall for 30 minutes because, incidentally, the wall just might provide the information or motivation needed to finish that paragraph'.
I'm just kidding, but seriously, do walls contain academic information?
These are the distractions that distort the flow of information from brain to paper, and I can totally relate.
I can also relate to the solitary/public writing contradiction.
At times, that ambient music may be substituted by background human conversation. Coffee shops are ideal for this because, like us, some people there to write and read, too.
Sometimes just being in spaces where other people are writing is enough to motivate me to work. Is this the case for you as well? Monkey see, monkey do, I guess!

**Zack:**
I think it also has to due with the upbeat tone that occurs in these kinds of public environments.
Not only are other people doing work in coffee shops, there are people moving around, being playful, and in general the room is energetic.
I think that as I'm placed in this kind of environment, I adopt similar behaviours or mindsets that the people or environment exhibit.
I think that the overall ambience of a situation or setting has a lot to do with how I write.

**Andy:**
"Sometimes just being in spaces where other people are writing is enough to motivate me to work."
Yes.
And this, again, is the need to make writing a social practice, not something you chain your desk to do...to remind you, in a way, that you are writing for others as well well as yourself.

**Annabelle:**
I completely relate when you say you need to isolate yourself.
I too like to listen to music to do so but I unfortunately can't listen to anything with lyrics or else I will start to sing along.
I also wish I could go to a coffee shop to write (there are so many nice ones!) but I find I end up people watching as it is more interesting then what I am trying to accomplish.
I completely agree that I need to clear my desk and computer screen so as to not be distracted.
Do you find you work better at a particular time of day?
To be in a busy setting I imagine that the afternoon would be the most productive.

**Zack:**
I usually shuffle around for a bit in the morning, reading interspersedly while clearing some housework out of the way.
I have a hard time sitting still for long periods of time so the on-and-off reading keeps me from getting bored.
Also, I find that doing mundane tasks like clearing clutter or laundry give me a chance to reflect on what I just read.
In the end I generally start writing at around noon.

**Jonathan:**
Zack, that's interesting that you like noise going to in the background while you are writing.
I find that my tendencies are the opposite, and that complete silence is the only way for me to focus.
In fact, your type of background noise is what tends to put me asleep as I find it distracts my mind.
Also, I like having items I need to write far from arms length so I am given an excuse to take a break.

**Ani:**
Hi Zack
Thanks for an interesting post!
How did you realize that you worked better in bustling environments?
Having enjoyed the links you've shared with the class, I'm curious about the role(s) that online readings play in your writing process.
You mentioned starting your work day by finishing things, like email or readings, that might weight on your mind and distract you while you work; but also how "on-and-off reading" help you stay alert and interested.
I have a similar approach; I engage in intermittent reading when trying to write, as a way to lure my brain into a certain linguistic style or to help myself get the distance necessary to think more broadly about a question.
In practice, though, reading often ends up being a procrastinatory tool more than anything else.
How do you manage to get the positive sides of the distraction that reading provides without falling prey to the negative ones?

**Zack:**
Hi Ani.
Like you wrote in your post, I too go back and forth between reading and writing.
It does help me develop tone, but it's mainly because I'm not so great at taking notes while reading.
I always end up checking the original text of the source I'm citing at some point because of my uncertainties in my notes, and then I get distracted by something I haven't noticed, or I see a related article in google scholar, etc.
I'm trying to work on my note taking to try and solve this issue.

