---
title: Writing the Field
date: 2013-01-18
categories:
  - Writing the Field
draft: true
---

This semester I enrolled in a writing course called _Writing the Field_ taught by Dr. Andy Roddick, and I am very excited about it.
I hope to gain more confidence in my writing, and be able to convey the thoughts in my head more clearly.
In addition to working on a piece of writing throughout the semester, one of the requirements is to maintain a blog.
Since I already have one I'll be writing the required posts here, in addition to my regular ramblings.
Here is an overview of what I'll be writing about:

1. **Your writing workflow:** a blog post on your writing process and a reflection of what slows you down, or where writer's block emerges.
2. **An outline:** a basic outline of the writing you wish to complete this semester.
3. **Review of a "Reviews in Anthropology" article:** find an article pertinent to your work and analyze the strengths of the literature review.
4. **Knowing your audience and recognizing the skeleton of written work:** annotations of three articles in three anthropological journals.
5. **The good and the bad:** discussion of what makes articles fail and succeed by looking at an excellent article and a weak one.
6. **Review of a good presentation:** within the department, at a conference, or from a youtube link.

I think blogging is a great medium for a course like this.
Blogging can help students gain confidence in their writing abilities, formulate ideas that can be shared and discussed, balance the formality of academic writing, and develop a presence among peers.
I find that blogging is easier to do than writing a formal piece, as I tend to consider blogging more "active".
I want this view to change.
Both blogging and "formal" academic writing should be considered active, and these lessons just described should be applied to any piece of work.
By the end of the course I hope I'll be able to apply my current mindset regarding blogging to other forms of writing as well.
