---
title: "Writing the Field - Blog #6"
date: 2013-03-12
categories:
  - Writing the Field
  - Citation analysis
  - Network analysis
  - Presentation
draft: true
---

For this sixth blog post for Writing the Field, I will review a very strong conference presentation.
My aim is to examine the structure of the presentation and other aspects relating to form and mode of communication.
I chose to watch a recording of Tom Brughmans' presentation titled [Networks of networks: a critical review of formal network methods in archaeology through citation network analysis and close reading](http://lecture2go.uni-hamburg.de/konferenzen/-/k/13939), which he gave at Digital Humanities 2012 at the University of Hamburg in July 2012.
Brughmans conducted a citation analysis centered on archaeological publications that utilized network analysis.
The research that Brughmans presents is very well suited for this conference, as he utilized network analysis to examine how others in his field have used these tools, which are often encompassed under the umbrella of digital humanities.

Notably, Brughmans does not use slide-based presentation software such as Microsoft Powerpoint or Apple Keynote, but instead uses Prezi.
Prezi allows you to present your work as if it is all laid out on a canvas, and enables you to zoom and pan along as you focus in on finer details or depict a broader scheme.
It is a highly visual teaching aid that allows a viewer to gain a clear conceptual picture of the content, akin to a map composed of many scales.
Prezi is especially useful to present research composed of various embedded components, such as Brughmans' work.
He examined how a set of 70 initial publications cited each other, and also looked at other 'degrees' of citations that extend from these initial works (the interrelations between all citations of these 70 publications, and all citations of these citations in turn).

Interestingly, I noticed that I focused less on the physicality of Brughmans, as I was so engaged with the visual aspect of the presentation.
However, he still maintained a presence as a narrator, guiding the viewer through the introduction, the data and methods, the various degrees of analysis, and the conclusions.
It's reminiscent of Khan Academy videos, wherein you only see the depictions of the concepts on a multi-scalar black background, drawn as you go along with the course, but you never Salman Khan's face.
One flaw I noticed, however, is that there were many long sentences used throughout, which Brughmans read almost verbatim.
Instead, I think it would be better to keep these points abbreviated, elaborating on them based on more detailed notes kept behind the podium.

Also interesting, is that Brughmans presented his work as a narrative, pointing out how his analyses either confirmed his expectations or surprised him.
When his results were unexpected, he explained his thought processes that led him to take the next step of his analyses.
Brughmans was also sure to point out the amount of work that he put in, especially regarding manual data entry.
This helped illustrate some of the limitations that he faced and how it would be difficult for anyone to overcome them, considering the size of the dataset.
In spite of this, It's a good way of showing to the audience that he was directly involved in collecting, mining, analyzing, and interpreting the data, and that this research was entirely dependant on his efforts.

Overall, I think that this presentation was very good.
I look forward to seeing him present in person sometime in the near future.

#### Comments
**Shawn:**
Did you note who was v. central?
*ahem* *ahem* *cough* *cough*

**Zack:**
Of course!
It would increase my eigenvector centrality as well (if my undergrad thesis was published, that is)

**Annabelle:**
Hi Zack!
I have heard of prezi before.
It seems to me that it really helps create flow into a presentation.
I'm glad the presenter was able to develop a narrative.
For the past few days I've tried to think about it myself and haven't come up with much.
Would you consider a similar narrative for your own presentations? Would you modify it?

**Zack:**
So far I haven't had much to present, so I haven't had much use for prezi as of yet.
I think it's best for recounting your mindsets at various phases of a research project, similarly to how Allen and Joyce (2010) describe some really engaging talks that strike the audience as a form of oral history, albeit in a metaphorical sense.

**Kat:**
Hey Zack,
I'm glad someone was able to discuss a presentation that utilized Prezi.
I've seen them utilized before and I've never fully appreciated the approach.
You have done a great job of explaining their use, but I usually find them quite distracting.
I think the concept of linking ideas is great, and your analogy of highlighting a canvas is quite good, but as a visual learner I have a harder time keeping track of how the ideas tie together.
I almost felt the need to have an overarching picture to see how everything was connected at a macro scale, to understand the  micro-connections they were making.  Do you think that there is a way that Prezi could overcome this issue, or that it is sufficient the way it is currently?

**Zack:**
Well, I wouldn't put all the blame on the tools.
I find that people tend to use novel tools just for the sake of using them.
I think prezi is versatile enough that it can be moulded in many ways, and used for a variety of purposes, but there are 'rules', just as there are standard aspects of utilizing powerpoint.
Practically every university has a webpage describing how to 'properly' design a powerpoint presentation.
I'm sure if one would look closely enough, some common features of great prezi presentations would come to light, and standards would become apparent.
In short, both powerpoint and prezi have their limitations.
They enable people to convey an idea in different ways, but a certain mode of communication may not be suitable for what the presenter has in mind.

**Shawn:**
It's all about metaphors.
If your material is suited to a metaphor of movement, of zooming, then Prezi is a natural fit (if well designed).
I could imagine doing a presentation about an archaeological site that first zoomed through from Google Earth, to pre-excavation pics, to post-excavation pics, to individual contexts, to records, etc.
Instead of presenting it, one would leave it up on a website to encourage non-linear exploration of the site.
...but of course, movement for movement's sake just induces vertigo...

