---
title: Introduction to Outer Space
date: 2013-04-26
categories:
  - outer space
  - sci-fi
  - the future
draft: true
---

As an avid sci-fi fanatic I'm extremely interested in the ways that different kinds of people perceive the future.
Recently I've been exchanging letters with my 102 year-old great aunt who, despite her age, is not lacking any curiosity about the world around her.
I'm always interested in her opinions about the future, because she has lived through so much and has remarkable experiences to base her visions on.
Lately we've been talking a lot about space exploration and the things that humankind has accomplished, and what we have yet to achieve.
I've been trying to find some books to send her and I found a document published in 1958 called [Introduction to Outer Space](https://en.wikisource.org/wiki/Introduction_to_Outer_Space).
This pamphlet was published by U.S. President Eisenhower's Science Advisory Committee that explains some of the details that are faced when launching satellites, rockets, and other kinds of vehicles and equipment into space.
This pamphlet was originally addressed to the former president himself and was therefore written in a way that a layman (or even a politician) could understand.

It's a very interesting read, highlighting the general attitude towards space exploration during the late 1950s, 11 years before humans stepped foot on the moon.
It also includes a general timeline of research objectives and potential feats that scientists of the time believed would be accomplished soon.
Among the items on this list, only one is still incomplete.
