---
title: Star Trek and Classics
date: 2014-09-01
categories:
  - Star Trek
draft: true
---

Star Trek may best be viewed from the eyes of classicists.
Classics is normally associated with the study of Greek and Roman culture and civic society during their respective classical periods, and the particular focus on these areas of interest is deeply rooted in western European socio-political ideals and scholarship that emerged from the Renaissance to the late 19th century.
While critics of the discipline point towards the extensive research that has been done on these particular geographical and temporal settings as detriments, I believe that classics is really about the study of specific kinds of societies from a particular angle that emphasizes attention towards the nature of civic society, relationships between foreign and domestic affairs, and the impact of myth and public memory on contemporary society.
While many classicists today may not realize it, this definition certainly does not limit classical research to ancient Greece and Rome.
These issues were faced by many societies throughout history, and persist today.
These are themes that are even commonly dealt with in fiction!

As my first classics professor taught me, the discipline in called classics because it is the study of a society that is considered to be in a class of its own.
Under this definition, classics may be broadened to include the study of notable societies for which detailed material and textual evidence is available, examined through a critical socio-political perspective.

[This post was never completed.]