---
title: Migrating from wordpress
date: 2025-03-09
aliases:
  - https://blog.zackbatist.info/2025/03/09/migrating-from-wordpress/
categories:
  - meta
  - writing
  - website
draft: false
---

I'm moving my blog from WordPress to a [quarto](https://quarto.org/)-based system, which I'm already using to maintain other aspects of my professional website. The blog is now located at [zackbatist.info/posts](https://zackbatist.info/posts).

I'm doing this for a few reasons:

- To make my site more consistent from a visitor perspective
- To match my other writing habits and workflows
- To save some money on VPS hosting
- I've been having some weird database corruption issues
- All the WordPress drama

This means that I'll no longer be using the [blog.zackbatist.info](https://blog.zackbatist.info) subdomain, and all existing links will be broken. I reformatted all the older posts and added the existing URLs to the new versions' metadata, but this won't actually do any active redirection.

I'm also shutting down my mediawiki instance ([wiki.zackbatist.info](https://wiki.zackbatist.info]), which I was barely using to begin with. I consolidated and refactored all the pages worth keeping and will continue to write additional notes at [zackbatist.info/notes](https://zackbatist.info/notes).

Please update your RSS feeds if you want to keep following!
