---
title: archaeological record
alias: https://wiki.zackbatist.info/index.php/Archaeological_record
---

The notion of the archaeological record encapsulates two quite different perspectives: first, as the totality of the material remains of past cultures found by archaeologists through survey or excavation, and second, as the documentary archive derived through a recording process from these material remains [@dallas2015]. The physical record of material occupies the empirical domain when materials are found, excavated, individualized and selected, and then subsequently represented, transformed and interpreted to construct a textual record. The archaeological record as a documentary archive, which comprises the traces and inscriptions of archaeological facts made in the light of the prior knowledge, middle range theories, intuitions, and sense experiences of archaeologists as they conduct their research, is constructed at the same time as its material form is irrevocably destroyed through excavation, gradually taking its place as evidence. These physical and informational aspects of the archaeological record each formulate the other. The informational archaeological record is recognized as a product of the physical collection and analysis of materials, and the physical record is formulated and delimited through the conception of materials by the minds of archaeologists. This way of thinking about the formulation of the archaeological record puts [activity](activity_system "wikilink") at centre stage. An archaeological observer is needed to intervene, who ascribes meanings to materials, who delineates natural phenomena from cultural processes, who differentiates signs of modern intervention from activities performed by the archaeological other, and who selects signal from noise.
