---
title: "Pruning open-archaeo"
date: 2024-02-02
aliases: 
  - https://blog.zackbatist.info/2024/02/02/pruning-open-archaeo/
categories: 
  - open-archaeo
citation: true
draft: false
---

I've been working with Joe Roe to analyze open-archaeo to better understand the community of practice around archaeological software development. This prompted us to go back and remove records that are arguably out of scope. We identified a few dozen items that don't really fit with our objective of assembling software made by archaeologists for archaeological purposes. Many of these are general-purpose tools that happen to be relevant to archaeological use-cases, and whose contributors and primary maintainers are largely, if not entirely, comprised of non-archaeologists (e.g. [xraylib](https://github.com/tschoonj/xraylib), [QField](https://github.com/opengisch/QField)). Others deal with specific processes that form parts of methods from other disciplines that archaeologists have come to work with and rely on, such as genetics, ecology and earth science, but which seem too distant from archaeology to warrant inclusion in open-archaeo.

It's a bit jarring to make such a big update — especially one that removes around 15% of the dataset — so soon after we published a [data paper](https://doi.org/10.5334/joad.111) about it. However, that paper was meant to communicate the data collection methods, the data structure, and the rationale, purpose and value that underlie open-archaeo and its continued development. We have always been very clear and upfront that this is a live project, but it's still a bit awkward trying to align our work with more traditional forms of scholarly communication that are suited for more stable outcomes than what continuous and open-source projects afford.

You can see the changes in [this git commit](https://github.com/zackbatist/open-archaeo/commit/c801a3ca46796c5099c33d8be7d08c9b44516a62). Don't hesitate to get in touch if you have any questions or concerns. This is still a community effort and I could not do this without all of your contributions 🙂


