---
title: Recreating a Bronze Age Wine
date: 2011-11-19
categories:
  - Alternative learning
  - Biomolecular archaeology
  - Wine
draft: false
---

This week I started a project for one of my courses, _Themes in Interdisciplinary Inquiry_ taught by Dr. Marc Tyrrell, that is somewhat related to my honours project.
I'm looking into how the inhabitants of the Bronze Age Aegean produced and prepared wine, and I'm trying to reproduce some of the process by making my own.
Of course I am limited by time and monetary constraints, but I am still learning a lot by doing research, and my report at the end of this project will consider things that I could not replicate.

I'm treating this project like an experience, rather than just a typical paper.
Instead of doing plain research and spitting out a 20 page assignment, I will complete a report documenting the actual production method that the Minoans and Mycenaeans used, and how it differed from how I am making wine.

One of the biggest problems that I encountered while setting this up was trying to find what herbs and spices were added to wine before and after fermentation.
There are no recipes documenting ingredients and their proportions recorded by Bronze Age scribes, although in later Classical, Hellenistic and Roman times such records do exist.
However, these additives can be identified using chemical methods, and [Dr. Patrick McGovern](http://www.penn.museum/sites/biomoleculararchaeology) of the Biomolecular Archaeology Laboratory for Cuisine, Fermented Beverages, and Health at the University of Pennsylvania is making broad steps in this interdisciplinary junction.

In addition to the help of Dr. McGovern, I also got in touch with [Dr. Rod Phillips](http://www.rodphillipsonwine.com), a member of the History faculty here at Carleton who is a distinguished wine critic and writes a [weekly wine column](http://www.ottawacitizen.com/columnists/Rod_Phillips.html) in the Ottawa Citizen.
He also teaches courses about the history of wine and other alcoholic beverages, and is writing a book on the topic as well.

I find that having an immediate goal as opposed to a long-term accomplishment is very beneficial.
Especially if that immediate goal involves a nice bottle of wine waiting for me in a few weeks after the semester is done.
I think anyone could appreciate that.
