---
title: "A Re-Creation of a Bronze Age Aegean Wine: An Overview of My First Attempt"
date: 2011-12-23
draft: false
categories:
  - Bronze Age Aegean
  - Experimental Archaeology
---

As I promised here is a report for the Bronze Age wine that I made.

The consumption of wine in various ancient settings is a frequent topic of research in a number of disciplines.
Much of what is considered fact is based on indirect knowledge, derived from ancient texts, archaeological finds, or studies of linguistic variations.
The study of the consumption of food and drink in an archaeological context was inspired by anthropological interpretations of archaeological research, starting in the 1960s and 1970s with the birth of 'New Archaeology'.
This led to concepts that focus on the interaction of the human body with aspects and elements of the world around it, taking both biological and environmental variables into account [@kelley1990].
In recent decades there have been increasing numbers of studies of the use of psychoactive drugs that are used as medicinal agents, in religious rituals, and also simply recreationally.
A wide range of earlier cultures and societies have used psychotropic drugs in all of these contexts, and these have been explored in serious academic investigations, even though the use of these same agents may not accepted in contemporary society.
Indeed there have even been some disturbing instances when these contemporary cultural ideas concerning drug taking actually end up being reflected in the review process of these academic endeavours.
Not withstanding these exceptional cases, the ritual use of mid-altering drugs remains a subject of serious students of anthropology, psychology, religious studies and other disciplines.

Alcoholic beverages can also be included among chemical entities that can have mind-altering effects on people, and have been used in a wide variety of contexts throughout human history, ranging from religious ceremonies to recreational and social functions.
In contrast to psychoactive drugs, alcohol is generally an accepted aspect of most Western contemporary societies, so the study of its use in ancient societies is not as controversial.
Numerous academic and general-reading books about the histories of fermented and distilled alcoholic products have piqued public and academic interest, and stimulated further investigations that make the history of alcohol more than simply a few footnotes in a social history text.

I have a tremendous interest in the history of the consumption of mind-altering substances, specifically alcohol-containing beverages, in ancient times.
Much of my studies in a variety of courses during my university years have been devoted to this area of research.
Virtually all of my academic effort has restricted me to a desk in my home or a chair in the library.
One exception was a summer course at Washington University, which runs an archaeological field school at Tel Dor, south of Haifa.
While absolutely thrilling and captivating in terms of an ultimate career, I did recognize that though on the dig I was finding real examples of vessels that were used by the ancients, I was still not fully experiencing their actions and facing the challenges that they dealt with to fill those vessels.
This flexible final project offered me the fantastic opportunity to work on a hands-on project in order to broaden my perspective, and to try to experience something of what human ancestors did.
That is why I have attempted to concoct a re-creation of wine from the Bronze Age Aegean, applying the knowledge that I have accumulated throughout my undergraduate years and additional research I have undertaken.
My initial goal was to make a reasonably authentic wine that mimicked the process undertaken by vintners of prehistoric Greece, while taking into consideration the fact that I am limited by monetary and timing constraints.

Although I began this project with great expectations and enthusiasm, I had to face the fact that there were many shortcomings that rendered the process incomplete.
Firstly, I started planning for this project in late November, which is long past the harvest time for grapes.
This is true for both modern as it was ancient times in the Mediterranean.
In order to make my wine as authentic as possible, I should follow the instructions of Hesiod, who wrote his famous poem _Works and Days_.
It is about the daily lives of ordinary people, and he included a form of farmer's almanac that acted as a guide for agriculturalists.
Hesiod lived sometime between 750 and 650 BCE, which was around the same time as Homer.
The subject matter that the authors of this period wrote about was of the times of the infamous Greek heroes, whom supposedly were real people living in the Bronze Age.
Their achievements may have been exaggerated since these stories were meant to be conveyed orally, and were first written in by Homer and Hesiod in the Archaic Period, following the so called 'Dark Age' after the collapse of numerous civilizations at the end of the 2nd millennium BCE.
As such, they were subject to modification or enhancement, and their interpretations should be read with this in mind.
That is not to say that these epic poems cannot tell us very valuable information about the Bronze Age, and archaeological evidence can verify many aspects of these tales.

In this treatise, Hesiod advised farmers about viticulture and wine production.
For instance, he says that vines should be pruned and prepared for the 'rebirth' of the vine "when Zeus has finished sixty wintry days after the solstice, then the star Arcturus leaves the holy stream of Ocean and first rises brilliant at dusk”.
Hesiod also suggests approximate times for harvest, saying when "rose-fingered Dawn meets Arcturus, then cut off all the grape clusters and bring them home”.
These astrological events occur on a cyclical basis, and would correspond to the modern Gregorian months of February or March for the former and early September for the latter.

If I had had more time to prepare this project, I would of course try to replicate the timing of these crop cycles as accurately as possible.
However, due to the agricultural cycle of grapevines, no yearly planting is necessary.
Rather, vines lie dormant during the winter and become active again once the environment becomes warmer.
This does not mean that no labour is needed; a vintner must rearrange vines according to the orientation towards the sun, check the properties of the soil, and make sure that the vines stay tame and do not encroach on each other.

Interestingly, the difference between wild grapevines (_Vitis sylvestris_) and domesticated ones (_Vitis vinifera_) can be easily recognized based on their physical properties, before even looking at differences based on DNA sequences.
Grape pips have been found at numerous archaeological sites, and their morphology can help identify whether or not humans manipulated the growth of vines.
Although the changing shape of seeds seems to offer no competitive advantage from an evolutionary standpoint, they do indicate a switch from cross-fertilization to a self-fertilization method of reproduction.
Seeds from wild (sylvestris) vines are rounder, possess a nonprominent beak, and show an average seed index of averaging about 0.64 (ranging from 0.54-0.82) [@jackson2000: 21].
In contrast, seeds from domesticated (sativa) vines are more elongated, process a prominent beak and have a seed index averaging about 0.55 (often ranging from 0.44-0.75).” ((Ibid. 21-22.))
The seed index mentioned here indicates their ratio of the length and width.
This correlation between seed shape and cultivation is evident by comparing modern domesticated grapes with samples of _Vitis sylvestris_, and measuring morphological differences between the two.
In addition to different seed sizes, other phenotypic features that indicate differences between cultivated and non-cultivated vines include grape colour and the growth of flowers, although these are not evident in the archaeological record [@this2007].

Evidence for grape growing has been found at numerous archaeological sites, the earliest examples of which appear in the Caucasus region of Georgia and Turkey.
Domesticated seeds have been found, dating to around 8000 years ago [@this2006: 511].
Additionally, wine residues have been found in jars at Hajji Firuz Tepe, located in the Zagros Mountains in modern Iran [@this2006: 511].
By dating the ceramic vessels, we now know that the earliest instance of wine being made was between 7000 and 7400 years ago.
A link between the domestication of the grape and wine production is clearly evident, but defining which came first is still being debated.

Even though the technology existed elsewhere, viticulture was not developed in Greece until the Final Neolithic period, at around the 3rd millennium BC.
The earliest wine press in the region was found at Myrtos on the southern coast of Crete, and suggested large-scale production of wine [@mcgovern2009: 184-185].
This knowledge and technology was likely imparted to the island from the near east, brought by Canaanites or Phoenicians who would benefit by expanding their trade routes deeper into the Mediterranean.
In fact, Canaanite wine jars from the Bronze Age have been found scattered around the southern Aegean, and trade routes discerned by modern scholars suggest that Crete was a major stop [@leonard1996].
Cretans may have then passed on the technology of winemaking to the rest of the Aegean to the north, and to mainland Greece as well.
Grape pips have been found in jars and large fermenting basins at certain islands in the Aegean (Syros, Amorgos and Naxos) [@mcgovern2009: 186], at other palaces on Crete (Phaistos, Palaikastro) [@nunez1989: 223], as well as on the mainland (Aghios Kosmas) [@mcgovern2009: 186].
At these locations, the scripts that were used to describe vineyards, grapes, and other wine-related words, were derived from Egyptian Hieroglyphics, which suggests a chain of culture, at least in regards to wine [@mcgovern2009: 186].

Although the exact variety of grape that was first domesticated in Greece is not definitively known, there have been many studies that attempted to pinpoint the genetic diversity of grapes of the Eastern Mediterranean region.
It is widely suggested that Muscat was the first cultivated grape in Greece, however this broad category encompasses many sub-varietals [@crespan2001: 23].
The methods used to come to this conclusion involved tracking recessive genotypes from modern vines, and comparing genetic markers that indicate genetic mutations of the plant.
Most of these studies are multi-disciplinary in nature, and include the analysis of ancient texts and material and botanical evidence found at archaeological sites as part of the process of mapping the genetic diversity of grape vines.

Knowing the general type of grape that was widely used in Greece close to the time of initial domestication, I could attempt to make my reproduction of Bronze Age wine more authentic.
I sought out any kind of Muscat grape, which was a big challenge.
What I eventually found was a concentrate of Muscat grapes (since it was November I could not find anything fresher), although no specificity was given as to its sub-variety classification.
Even so, the exact kind of grape that was cultivated early on in Greece's history is not known, and so having more specific options would not have made much of a difference.

An additional step that should be taken in order to keep the re-creation as close to the original as possible, is to dry the grapes, which helps concentrate their constituent sugars.
Hesiod suggested that a farmer should "show them [the grapes] to the sun ten days and ten nights: then cover them over for five, and on the sixth day draw off into vessels the gifts of joyful Dionysus”.
The fermentation of dried grapes can potentially produce higher alcohol content since there are more sugars that can be converted into alcohol.
However, the main limiting factor of alcohol content in all wines is the capacity of yeast to survive in high-alcohol environments.
If low-capacity yeast is used then the wine will be very sweet since the microorganisms will die early on as a result of the alcohol, and the additional sugars will not undergo fermentation.
In order to replicate this sweetness I could either follow Hesiod's suggestions and dry the grapes, or since I used grape concentrate I could add less water to maintain higher sugar concentrations and replicate the same effect.

In the case of the wine I have produced, I was forced to use a concentrate, since it is impossible to obtain whole or crushed grapes so late in the year, especially in such a cold climate like Ottawa.
Because of the sticky consistency of the solution, I had to add more water, which seemed to be counter to the ancient procedure that Hesiod described.
However, another form of sugar could be added to modify the inaccuracy this deviation could produce.
Biomolecular analysis of residues inside ancient pottery has confirmed that honey was often added to prehistoric Greek wines, so I decided to use add some in order to maintain the sweet flavour that was intended.

Other additives have also been found to be have been mixed with wine made in the Eastern Mediterranean during the Bronze Age.
Although not much is known about herbs and spices added to wine in Greece specifically, evidence of such modified wine exists in Egypt and the Near East.
Because of the lack of information about wine additives in Greece during this time period, I used spices and herbs that have been found at these nearby archaeological sites in this project instead.

At the tomb of Scorpion I located at Abydos in Egypt dating back to around 3150 BCE, dozens of wine jars were found containing intact residues that could be characterized.
Using chemical analysis techniques, many fruits and herbs have been identified by investigators in these jars, including figs, savory, balm, senna, coriander, germander, mint, sage and thyme [@mcgovern2009: 166].
Of these, I used thyme and pennyroyal (a type of mint), in addition to the honey that was mentioned above.
Not all of these spices were found together in the same ancient containers, and the ratios amongst them that were used are virtually unknown.
Because I could not find out about these specific factors, I mixed spices that I assumed would taste good together, based on my own experiences.

Even though there is not much physical evidence of additives that were used in Greek wine, there have been some finds of residues of kykeon, which is a mixture of wine, barley and herbs.
This drink was a penultimate part of the Eleusinian Mysteries, a religious festival centred around the worship of Demeter during the Classical Period in Athens.
This beverage also is mentioned in Homer's Iliad and Odyssey, which suggests that it was consumed in older times as well.
As a part of the Eleusinian Mysteries, kykeon was highly regarded for its psychoactive properties, which stemmed from the addition of ergot, a fungus that may have simulated the perception of spiritual experiences associated with the festival [@wasson2008].
Also, the fact that worshippers would consume kykeon on an empty stomach after a long fast may have enhanced the effects of the hallucinogen [@roberts2000: 11-12].

The study of kykeon as it pertains to the Classical Period is quite interesting, but it may have little relevance to the nature of the drink and its social implications in prehistoric times.
However, I include it here because kykeon is mentioned in Homeric epic, and the makeup of this drink is even described in Homer's <em>The Iliad</em>:

> In this [the infamous Cup of Nestor] the woman, as fair as a goddess, mixed them a mess with Pramnian wine; she grated goat's milk cheese into it with a bronze grater, threw in a handful of white barley-meal, and having thus prepared the mess she bade them drink it.

In this passage there is no mention of any psychoactive ingredients, however this is not necessarily the case regarding the drink referred to in Homer's other famous tale, _The Odyssey_:

> When she [Circe] had got them into her ouse, she set them upon benches and seats and mixed them a mess with cheese, honey, meal, and Pramnian but she drugged it with wicked poisons to make them forget their homes.

After Odysseus' crew drank this mixture they were supposedly turned into pigs, which can be interpreted as either the affects of a hallucination caused by the "wicked poisons”, or simply intense alcoholic inebriation.
Also in The Odyssey, kykeon was used in an offering to Hades in order for Odysseus to enter the mystical underworld.
The significance of kykeon in The Odyssey suggests a strong tie between this epic tale and the Eleusinian Mysteries, since some of the rituals associated with the Classical festival allude to some of these instances, such as the sacrificing of a piglet and its association with the underworld, which is a very significant theme of the worship of Demeter.
Although I will not go into more detail concerning the connections between kykeon as it pertains to Homeric times and to the Classical Period, it is important to note that these ties exist, and that kykeon held religious significance.
Because I wanted to recreate a Bronze Age wine that was commonly consumed on a daily basis, the goal of this project was not to make kykeon, although researching this topic did provide insight concerning the use of psychoactive chemicals in ancient times.
In either event, I decided that even if I could find them, I would not add psychoactive drugs to our wine.
It is enough to simply know about this particular variation on wine amongst the ancients.

The study of alcoholic beverages requires some knowledge from other disciplines, including microbiology in order to better understand the process of fermentation.
Fermentation is the transformation of carbohydrates (usually in the form of sugars) to alcohol, by the natural processes of yeast or other single-cell organisms.
A variety of strains can be used in modern winemaking, and each can contribute unique properties to the finished product.
However, the discovery of yeasts only occurred in the 1850s, when Louis Pasteur laid out some of the basic principles of germ theory.
Before yeasts could be studied under a microscope and cultured for experimentation, very little thought was placed on the fermentation process; it simply happened.

It is likely that the yeast used in winemaking all around the world in ancient times was the strain _Saccharomyces cerevisiae_ [@dugan2009: 25].
This species inhabits the skins of grapes, and once they are crushed, acts on the juices that contain large amounts of sugars.
This yeast is very commonly found in nature, and is even viewed as a teaching model in microbiology and other related disciplines because of its simple structure and behaviour.
Because of the likelihood that this strain of yeast was used in the Bronze Age Aegean, I incorporated it into my wine making process.

Another aspect of the ancient wine making process is the fermentation vessel.
Archaeological excavations at Bronze Age sites around the Aegean have turned up large-scale wine making facilities, as noted above.
At these installments giant pithos jars have been found that usually contain grape pips or residues that have lasted the test of time.
These are often found underneath the normal floor level, which would help keep the temperature within the vessel regulated while the must ferments during the autumn and winter months after the harvest in September.

These large vats were usually non-glazed on the inside, since they are simple utilitarian vessels.
Thus, the fabric is very porous and susceptible to leakage.
Also, if excess water seeps into the ceramic and freezes, this can causes stress on the material due to the expansion caused by the more organized molecular structure of solids.
In order to counteract these problems, pine pitch was used to coat the inside of the vessel and keep liquids from seeping through [@romanus2009].
This would reflect in the final product, and effect how the wine tasted.
In fact, later on in Greece's history, pine resin, which is the derivative of this kind of pitch, was added to wine intentionally to make a specialty wine called Retsina.
Greeks still produce Retsina today, and its production represents one of the longest lasting uninterrupted cultural traditions that the world has ever seen.

Because of another limiting factor, I could not coat the inside of my fermentation vat with pine pitch.
The short amount of time I had to prepare for this project did not allow me to obtain a vessel similar enough to an authentic pithos that could also be used to make a consumable food product.
It is very hard to find large utilitarian pottery, as most of the tasks for which pottery would be used in ancient times now employ plastics or alloyed metals.
This is especially true for cooking ware, as it is impractical to use inefficient and breakable pottery for various tasks in the kitchen when a cheaper, reusable, and dishwasher friendly alternative is readily available.
That is not to say that ceramic kitchenware does not exist, but it is almost always tableware rather than used for food preparation, and is certainly always slipped or glazed in order to maintain health standards.
Because of these factors, these kinds of ceramic vessels would not be suitable for this project.

Even if I were able to find a large enough glazed vessel, the pine pitch would slide off the inside walls, and would not be able to seep within the open pores that a coarse vessel would have.
Of course I could just add pine pitch to the must to replicate the flavor, but that also has its own set of complications.
Some harmful chemicals are also made from the resin of various trees of the pine family, including turpentine.
The ancients may have been ignorant of the fact that certain things that they put in their wine (including lead) were very dangerous to human health, but that does not mean that such dangers can be ignored simply for authenticity's sake.
Obviously I would not endanger the lives of anyone who drinks my wine.

However, one spice that was added to my wine is pennyroyal, which is a variety of mint that has been used for millennia for its medicinal properties.
It has been infused into a variety of mediums, including tea and wine.
Studies have shown that pennyroyal can induce abortions, and thus should not be consumed by pregnant women [@sullivan1979].
It is now appreciated by the medical community that drinking alcohol during pregnancy can lead to birth defects for the child, and should be avoided all together.

Once I had all of the components of our wine selected and mixed, the next decision would normally have been with regards to the duration of fermentation.
While I was unable to find a specific source from the ancient Greeks to guide me on this, I can only surmise that fermentation was allowed to proceed without interruption until all of the yeast was spent.
I had only two weeks for the entire process, given my goal was to share the finished product by the specific deadline.
As a result, I was forced to stop the yeast's work slightly early and before the process ran its natural course.
As a result my wine is quite sweet.

The last step of the wine making process is to decant the finished product into smaller bottles.
For my wine, I used standard 750 ml bottles that are commonplace today, and are regulated by the strict standards of the Liquor Control Board of Ontario.
However, the ancient Greeks transported their wine in amphoras, which had a specialized design that helps ease the shipping process.
To pour the wine from the pithos into the smaller jars, a pre-made hole that was sealed with wet clay prior to fermentation would be opened and the wine would flow through [@hamilakis1996: 14].
Once the wine was collected, dense clay lids were used to close the narrow amphora necks, which were sealed with wet clay or slip.

When consuming their wine the ancient Greeks did not pour directly from the amphora, but rather decanted it again into a communal serving vessel.
Wine was rarely served neat, and was diluted with water in order to maintain a steady yet responsible state of inebriation.
Hesiod advises that wine should be diluted with water at a ratio of 3:1 for an ideal mixture.

Although the wine that I have created is not a perfect re-creation of a Bronze Age example, I am still proud of my finished product.
What I learned while researching the process that the ancients employed may be very helpful to my later academic work, and provides a first hand experience that I would never have been able to otherwise have while sitting at a desk.
I now realize the potential of alternative education styles, and I hope to incorporate experimental archaeology throughout my career.

The process of making wine in the Bronze Age Aegean was actually quite similar to modern methods.
Essentially all that needs to be done is to plant and then harvest grapes, add any herbs or spices that are desired, let the must ferment, and then bottle and enjoy.
It is amazing that such a simple process was repeated by so many cultures across the world, in virtually all stages of known human history.
Although our understanding of the natural processes behind the wine making process are much more advanced, and we have learned to optimize the alcohol content, presentation, and aromas that constitute any given wine, the same principles are still there; wine and other forms of alcoholic drinks opens up relations between people, and acts as a social lubricant that plays significant roles in our social structure.

