---
title: On the Mycenaean Palatial Redistribution System
date: 2011-10-05
draft: false
categories:
  - Palatial Administration
  - Redistribution
---

Last week I wrote a short essay on the Mycenaean redistribution system, mainly focused on the palace at Pylos.
I realized that I did not know enough about the palatial administration in order to start focusing on the meat of my project, so this is mainly to provide background.
Keep in mind that this is not that detailed, and that I did not have too much time for this since I was spending time with family because of religious holidays last week.
But even though I didn't write this out in great detail I still learned a lot about the palatial administration, which was the main goal of this assignment.

For further reading I plan to read Karl Polanyi's book _Trade and Markets in Early Empires_ (1957), and the works of other authors that I stumbled upon while doing this such as Killen, Halstead, Wright among others.

---

## The Mycenaean Palatial Redistribution System at Pylos

The Mycenaean palaces are commonly viewed as economic centres, where raw materials, finished products, and allocations of land were recorded and redistributed among members of the palace and also among the.
The _damos_ were local communities that were ultimately under control of the palace [@shelmerdine2008a: 300-301].
This model of redistribution has been studied primarily by looking at the administrative records, in the form of clay tablets bearing inscriptions written in the language referred to as Linear B.
These documents recorded the flow of resources received by the palace, the process of turning these resources into manufactured goods by specialized workers, and the subsequent selective sharing of the finished products among the members of the community, among other economic concerns.
Essentially, resources were pooled by a central authority, and then redistributed to others.
This economic model was described and made popular by the economic anthropologist and philosopher Karl Polanyi, described this redistribution process from a cross-cultural perpective, and it has had significant influence on scholars in many disciplines [@polanyi1971].

Polanyi's model of redistribution was intentionally broad, so that it could apply to multiple contexts.
It can even be argued that 21st century Canada follows a redistributive system in a sense.
There is no doubt that the Mycenaean palace of Pylos conducted this sort of economic activity, but it is up to modern scholars to differentiate how Mycenaeans at Pylos mobilized and shared resources compared to how other societies managed their respective commodities.
@nakassis2011 [: 180] put it best:

> Indeed, the purpose of the concept of redistribution for Polanyi and his students was to allow them to investigate the differences between different redistributive systems, embedded as they were in society at large, not to construct a monolithic model of "redistribution” and apply it wholesale to different historical contexts.
> That is, we ought not to be discussing whether a given society is redistributive or not, but how it is redistributive.

This is a very important point, and discussing redistribution without a description of the particular context in which the concept is described, can result in misinterpretation.
Redistribution need not only refer to an economic system associated with a particular era, but it can be used to described social events in history as well.
For example, one topic of personal interest is about commemorative and ritual feasts involve consuming large amounts of resources, and these too can be viewed as a form of redistribution [@nakassis2011: 181].

There seem to be two main entities that constitute the Mycenaean economic organization: the palace and the _damos_.
The palace is often viewed by historians and Aegeanists as the central economic hub of a region, and was the domain of the ruler, known as the _wanax_.
The _damos_, on the other hand, were local communities that were run on a day-to-day basis by local people, but they were influenced by the palace.
In Messenia, the region under control of the palace of Pylos, there were 16 _damos_ that were mentioned in the tablets, which were divided into two provinces.
As inferred by the Pylian tablets, Ke-ke-me-na land was considered to be controlled by the _damos_, and Ki-ti-me-na land was under the control of the _wanax_or his kin [@shelmerdine2008a: 74-75].
Since ki-ti-me-na land was operated by the palace, resources generated by it were distributed to palace residents and those close to the _wanax_.
Land owned and operated by the _damos_ (ke-ke-me-na) was still indirectly restricted by the palace.
The _damos_ were taxed on important commodities and the distribution of ke-ke-me-na land among the elite members of the damos was controlled by the palace.
Thus, the _wanax_ could reward certain smaller communities by lowering taxes, and grant more land to individuals who supported him.

We can clearly see that the palace and the _damos_ were formally separate entities, but that the former still maintained a controlling influence over the latter.
The palace was obviously in a position to manipulate markets and costs in the _damos _to its own advantage.
The _wanax_used this power to solidify his rule by distributing land among his followers and rewarding those in his favour.
However, it is noteworthy that not all of the land in Messenia was recorded in the Pylian tablets, so the historical picture as documented in the written records is incomplete.
@lupack2011 [: 213-214] suggests that there were large tracts of untaxed land that is not accounted for, and even proposes that the religious sphere held its own land, independent of the palace.
So, it is at least possible that the _wanax_ did not control all of the _damos_.

Some industries were heavily controlled by the palace, and the entire process from harvest of raw materials into their manufacture into finished products was duly recorded.
@schon2011 provides an overview of three such industries, showing exactly how much control the palace had over them.

The palace also employed the ta-ra-si-ja system to influence certain industries.
Using this system, resources were allocated to craftsmen to make a finished product, which would be distributed by the palace.
@killen2001 noticed that this system was used mainly under certain circumstances: in decentralized industries, industries that only required one raw material, and industries that employed low-level workers.

The administrative system of the Mycenaean states, was evidently organized, yet there seems to be a lack of standardization in regards to the management and mobilization of resources [@schon2011: 220].
As noted, even though the _damos_ were somewhat autonomous, the palace and the elite supporters of the _wanax_ had a lot of control over the distribution of land and the manufacture of finished goods.
However, it is very important to note that the evidence used to study the redistribution systems of the bronze age Aegean are limited, and many things that were not recorded by the palace scribes remain unaccounted for.  Additionally, the research concerning the economic administration at Pylos can not necessarily be applied to other territories on mainland Greece since there were almost certainly regional differences.
While I will use analyze the redistributive model using network analysis in my thesis, I remain aware of its limitations and of the need to place it in context.

## References
::: {#refs}
:::
