---
title: Visiting McMaster and house hunting in Hamilton
date: 2012-05-27
categories:
  - grad school
  - Hamilton
  - McMaster
draft: false
---

This weekend I was in Hamilton visiting McMaster and hunting for a place to live.
I went with my parents because they're pretty good at this sort of thing.
The first thing we did was go to the campus, which is amazing.
It's so green and lush, and the buildings all have interesting designs.
I love how the campus is all hilly, and there are so many large trees that must have been growing there for ages.
It was a bit quiet since it's summer and it was on a Saturday but I got a good impression of the place where I'll be spending the next few years.

As for the house hunting, I trekked all around the Westdale area trying to find a good fit.
I finally settled on an attic room in one house that is less than a minute away from campus.
The location is amazing, the house is being fully renovated and the landlord is very reliable.
I really like the general area as well.
There is one fantastic coffee shop in particular where I spent some time.
Overall I'm really excited about this shift and I think that this is a good environment for me.
