---
title: The honours project... it is finished!
date: 2012-04-05
categories:
  - digital archaeology
  - honours project
  - last day of classes
  - The Connected Past
draft: false
---

So I finished my last class of the year today.
Actually, it was the last class of my undergraduate degree here at Carleton.
Although I still have some exams, it still feels like a weight has been lifted.
I also submitted the final copy of my honours project, and even though I enjoyed doing it I'm glad it's over.
I know that I'm going to pursue network analysis further in grad school, but right now I need a little break.
Dr. Graham sent me an [overview of The Connected Past conference](http://archaeologicalnetworks.wordpress.com/2012/04/05/an-overview-of-the-connected-past/) that was held at the University of Southampton last week, and looking over the presentations confirms in my mind that what I have been working on is quite relevant today, and has many great applications.

Since it is quite long, I'm not going to publish the full text on this blog.
Instead, click here to access the pdf.
Also, I'll be publishing my dataset and related materials on [OpenContext](http://opencontext.org/) and I'll post about this once I get everything organized, probably after exams.

And just because this project is over doesn't mean I won't be blogging anymore.
In fact, I'm just getting started.


#### Comments:
[**Tom Brughmans:**](http://archaeologicalnetworks.wordpress.com/)
Cool stuff Zack!
Looking forward to hearing of your postgrad network project.
And maybe we will see you at the next Connected Past.

**Zack:**
Thanks! I'm looking forward to it.
