---
title: New York, New York
date: 2012-02-29
categories:
  - travel
  - grad school
  - museum studies
  - Metropolitan Museum of Art
  - American Museum of Natural History
draft: false
---

This past weekend I travelled to New York with my parents to visit my sister for part of my reading break.
It was kind of last minute but I had a great time.
I spent most of my time by myself, which is alright because I love wandering big cities alone.
I like exploring at my own pace, seeing the people go by and being a part of it.

On the first day I went to the American Museum of Natural History, and I was actually quite disappointed.
There were dozens of little kids screaming in the halls and I instantly got a headache.
Many of the exhibits echo like mad so that only made it worse.
In fact, I found that the building was really run down and that the exhibits were all spatially confusing.
I couldn't stay for too long because I was so fed up, and my expectations were so much higher.

But the next day I went to the Metropolitan Museum of Art and it was amazing! This was one of the best museums I've been to.
I spent a lot of time in the Egyptian exhibit, as well as the one displaying artifacts of North and South America, Australia and the Pacific islands.
One piece that really stood out to me was a stone sphinx which was carved meticulously out of stone.
The veins of the stone perfectly match up to the shape of every curve, which is extraordinary.

I also got to see a friend from the field school I was working at this summer.
Gideon goes to Columbia, studying evolutionary biology, and I got to see some of the campus.
I also went to the Institute for the Study of the Ancient World, who offer a PhD. program at NYU.
There were no exhibitions going on at the time but I got to ask questions about the program and it's a definite possibility that I will apply there after my Masters.

Also, I got into the Master of Museum Studies program at University of Toronto so I'm very excited about that.
I'm really interested in the prospect of working in a museum, and I'm seriously considering going this route.
Seeing the MET in New York really inspired me to go in this direction.
