---
title: First impressions of McMaster
date: 2012-09-06
categories:
  - grad school
  - McMaster
draft: false
---

I'm finally getting started here at McMaster's Department of Anthropology, and I have to say, this school rocks.
The people within the department and the School of Graduate Studies are all very welcoming and I'm finding my place easily.

I'm under the supervision of Dr. Tristan Carter, and we've discussed possibilities for my research.
Although I haven't determined specific details, I'll be focusing on value and exchange in the prehistoric eastern Mediterranean.
Also, I don't know much about my role as a TA yet but there was a set of workshops I attended which really boosted my confidence in my ability to teach.

I really love the McMaster campus.
There is so much green space, the buildings have charm, and I've spotted some wildlife here and there.
This is a good setting for a new phase in my life to unfold.
However, there are some issues at home.
Typical roommate annoyances, lack of an internet connection (which will only be DSL when it finally gets connected), and tons of spiders in my new attic room.
I guess this will encourage me to get to campus more often and focus on work rather than deal with those issues at home.
