---
title: sci-fi and antiquity
date: 2013-12-17
draft: false
---

As an avid watcher of sci-fi, and as a student of antiquity, I like to think about how others view the past, the present and the future.
Science fiction, which is often co-labelled as speculative fiction, is an avenue for presenting the author's view of the world under different circumstances.
A writer's view of the future is shaped by his outlook on the world, his attitudes towards broader aspects of his culture, and his interpretation of the past.
Similarly, historians write their histories from a certain perspective, which is built up by their own personal experiences, their cultural context, and the academic traditions that have sculpted their interests.
I was speaking with a friend about the similarities between the production of science fiction and the study of antiquity, and I want to share some aspects of our discussion and the thoughts that spun off from it.

L and I were discussing this side-project I'm working on that I'm really excited about.
I want to write an epic story that occurs in a post-Iliad setting, along the same timeline as The Odyssey, The Aeneid, and the major dramas of the Classical Period of Greece.
I also want to incorporate an archaeological spin, tying up the storyline to what is evident today in the archaeological record.
I don't want to reveal too much just yet, I'll post some more about this later as it develops.
The fact that people have been telling these epic stories for generations amazes me, as it's a way of escaping the contemporary world and situating oneself with the legendary kings of the Aegean, the gods of Olympus, and the adventures that ensued.
Among the citizens of Classical Athens, hearing The Iliad being recited must have given a very amazing take on the past; conflicts between polities, military commanders leading armies to war, long journeys interspersed with hazards and oddities along the way.
Sounds a lot like Star Trek, doesn't it?

It also gave ordinary citizens the ability to step into the shoes of the main characters.
One could see how a great king would take control of his troops, deal with the interventions of the gods, and tackle the issues that lie in his way.
Additionally, there are a few instances when the role of the individual citizen is examined.
As an example, the common soldier Thersites, described as the ugliest man who came to Troy, criticized Agamemnon's leadership and is exemplified as a fool for doing so.
Battle scenes are also very illustrative as microcosms for everyday life.
By depicting the actions of common men in a certain light, and highlighting possible consequences, these stories associate certain attitudes to various behaviours.

Now, when retelling the innovations of the Classical Period in Athens, scholars base their views on generations of built-up attitudes towards these periods that have accumulated over centuries.
We emphasize the roles of the major politicians and tyrants as if we fully understand their ultimate goals and their decision-making processes.
However we only understand a certain aspect of their lives.
By writing fictional accounts of these characters, with a strong base in our current understandings, we can explore different facets of their lives and consider how they would act in certain novel situations.
The author can feel free to invent new characters, develop original story lines or even transpose an entire genre.
The developments would reflect the author's interpretations, and if I was writing I would try to base it in our current understandings as much as possible.
I would experiment and see how our view, formed over 2000 years of experience in between, complements my own understanding of this character and of this setting.

Essentially, you could call this fan fiction, and this is certainly not meant in a negative way.
By repositioning our understanding of the past, and by extending our own perspectives in a creative, perhaps even playful way, it is possible to get a more _real_ view on a setting of personal interest.
