---
title: "Writing the Field - Blog #3"
date: 2013-02-11
categories:
  - Writing the Field
  - regional analysis
  - review
draft: false
---

This third blog post for Writing the Field is a review of an Annual Reviews of Anthropology article.
The article I chose to examine is titled [Aspects of Regional Analysis in Archaeology](https://doi.org/10.1146/annurev.an.06.100177.002403) by Gregory A. Johnson, published in 1977.
Although it is not so recent, this article covers some fundamental developments regarding regional analysis in archaeology.

This article is very well laid out, starting with an overview of the broader assumptions archaeologists make regarding human decision making, and how these variables translate to our ideas regarding spatial interaction.
Johnson then goes on to evaluate how these variables are applied, choosing to examine gravity models in greater detail.
By discussing some of the key concepts that underlie this kind of model, Johnson prepares to engage the reader in discussions about how regional systems of interaction develop and operate.

The way that Johnson wrote this paper is well-thought out.
He starts off by pointing towards some basic concepts that underlie the study of regional interaction.
This allows non-specialized readers to engage with the language and the modes of thought that are commonly utilized when discussing such topics.
Then he utilizes the gravity model to show how these fundamental principles can be fitted together in order to examine regional interaction, and also describes some deficiencies of this concept.
By pointing out flaws associated with use of the gravity model, Johnson actually enhances the reader's understanding of how the fundamental variables discussed earlier should be properly utilized.
Johnson recognizes this and even goes on to say that "if gravity models provide nothing else, they do encourage archaeologists to consider more systematically the variables involved in interaction" (Johnson 1977:487).

Once the reader grasps how to properly understand and interpret ideas relating to regional interaction, Johnson goes on to discuss more complex issues that have been tackled using such a perspective.
This portion of the article provides a more in depth look at the development of systems of interaction, which is embedded in discussions on the adoption of sedentary lifestyles and agricultural practices.
These topics could not have been discussed through a lens of regional interaction without a prior understanding of the concepts relating to this sub-specialty.

As much as this article is a review of contemporary discussions concerning the development of systems of interaction, it also acts as an explanatory piece that shows how to properly formulate and interpret ideas relating to this sub-specialty.
In addition to reviewing some basic principles of the study of regional interaction, Johnson highlights some novel ways of thinking about state formation, the growth of certain sites over others, and the development of hierarchies.
These ideas all fit within the framework that he develops throughout the article, building upon examples that were mentioned earlier.

#### Comments
**K-Bish:**
Hello Zack!
Thanks for providing an interesting review on archaeological theory.
This is a topic I am less familiar with, and I am curious if you felt that Johnson's work would be accessible to an audience that has a similar lack of background.
I know that we had discussed the year of publish (1977) may have posed a problem for reviewing this article, but are any of these topics still applicable to your research today?
Or, do you feel that most of what is discussed is no longer relevant in modern theory?  I find that some older theory papers provide an interesting approach to utilizing new theoretical models.
By looking at how drastic they may have changed, or what the major changes are we can map the changing paradigms or utilize different approaches.
Overall do you feel that Johnson had a take-home message, or a 'so what' statement? I find this the hardest aspect of writing a review and I am curious how he approached it.
Thanks for sharing!

**Zack:**
I definitely think that this review is accessible to a wider audience.
It starts off broad, and expands to cover more specialized issues. Although it is not stated as such in the abstract, I think that the prime 'purpose' of this article is to review how the basic principles we start off are applied, and how these base variables affect archaeological discussions that result.
I do think that this is very useful today, since regional analysis is still quite dependant on assumptions (regarding human decision making, minimization/maximization/optimization, measurement of distance/effort/time, etc) that influence what we choose to be base variables.
Of course, new developments have occurred since 1977, and new models should be reviewed, but the critical engagement presented in this text should be kept in mind.

**Annabelle:**
Interesting review!
It seems the article is very method based.
I was curious if it went back in time and explained the early theories then followed the evolution of theoretical thinking or did it restrict itself to the theories of the moment.
For example, my review article restricted itself to explaining concepts and ideas from the previous 20 years only.
Also, since the article is quite old, do you think a new review article is necessary on this topic?
Although the article I chose was fairly old too I know of many other authors and journals that have since published papers talking about evolution of theory and changes in the discipline.

**Zack:**
The review was fairly focused on method, and the way I see it the examination of gravity models was used in order to break down the variables considered.
Gravity models were being borrowed from Geographers at the time, and they are used today in archaeology to a very limited extent.
This review was definitely written considering contemporary issues of the time, making frequent references to Hodder and Orton's 'Spatial Analysis in Archaeology' that was published a year earlier.
This review isn't so much an overview of recent developments as a critical engagement with contemporary thinking regarding spatial analysis in archaeology.

**Jonathan:**
Hey Zack,
As per our discussions when I drop by your office unannounced, I know little about population analysis, but im pleased you think this piece of theory is accessible to the layman.
Do you think you could expand a bit about gravity models and how they push the analyser to reconsider or at least confirm that the variables they are using are appropriate.

**Andy:**
Hi Zack,
You may want to search out the legacy of this older "Annual Review of Anthropology" article.
What has the legacy of this review been? How is it being cited in general?
In the last 10 year?
In the last 5?
And what are the key words for those using this article?
It is a very useful way to see how successful the issues have been, and how the areas of interest have morphed in recent years.
(Perhaps a more recent article has been written, but "framed" differently, using different terms of engagement?)
This would also be interesting as Johnson says on his very first page that he has assumptions about human decision making and spatial practices (energy minimization, etc) that archaeology (and particularly Hodder) has critiqued in recent decades.

**dillanejb:**
Hey Zack, I enjoyed your review.
A lot has changed, particularily in the field of spatial analysis, since this article was written.
Given your own interest in the technological, I would be very interested to know how you think the technological innovations of the last thirty years have impacted this kind of research.
Has that impacted on the themes Johnson discusses?

