---
title: "Outline for SP&L paper"
date: 2014-12-18
draft: false
---

**Main topic:**
How can a practice-oriented approach be useful for determining the ways by which the Halaf emerged, and for evaluating the distribution of its recognizable material manifestations?
.
**Intro:**
What is the Halaf?
What is the Burnt House at Arpachiyah?
What are the primary concerns of archaeologists studying these contexts?
Introduce the main question: How can a practice-oriented approach be useful for determining the ways by which the Halaf emerged, and for evaluating the distribution of its recognizable material manifestations?
What are the assumptions of scholars writing about this?
Preference for work at broader (regional and supra-regional) scales.
Agency often completely ignored, and replaced with reference to Barth (1969) or similar explanations for cultural contact or change.
At other times, the effects of agency are not viewed as transferable to broader scales, and tend to be compartmentalized to intra-site evaluations (examples...).
Looking at end products, not process or practice.
Lack of phenomenological or embodiment approach (van Dyke vs Chataigner and Barge?).
Always reverting to core/periphery model despite constant reminders to consider the role of nomads, to consider actions of individuals first and foremost in the construction of society rather than the other way around.

What are Joyce and Pauketat thinking? How does this relate to space, place and political economy?
Through collective action, individuals build society and decide how it is governed.
These actions, which effect the larger world around them, are manifested in the archaeological record in terms of practices, rather than end products.
Products/consumption may also be considered, but primarily in terms of how they allow one to experience the world through their senses (phenomenology) or through other aspects of their bodies (embodiment).
The meanings that people ascribed to places (raw material sources, natural environments, artificial structures, etc) may be deduced through examination of their behaviours and practices, as read through the material culture.
These interpretations may supplement or redirect our understanding of socio-economic/political ways of life.
If mapping or refining cultural boundaries is indeed the main goal, then this information must be mapped or visualized in an appropriate way --- highlighting different kinds of sites, kinds of interactions between them, and processes of raw material procurement or whatnot.

**Move to the data:**
How do these approaches (Joyce and Pauketat) relate to this specific context?
The re-examinations of the material from the burnt house at Arpachiya by Healey and Campbell make further interpretations of the same material easier.
Such re-interpretations would incorporate practice-oriented perspectives to some significant classes of material.
Obsidian will be the main material considered, but painted pottery may also be interesting to examine. However my experience with work relating to pottery may make this difficult, and I would have to rely on the prior work of others.
The burning of the Burnt House will also be crucial to evaluate from an agent-based and practice-oriented approach, but I'm unsure about how to situate this in the paper.

**Network analysis:**
Dataset will include all sites in the "zone of Halaf influence", including those with only 1 artefact.
Might have to look at the sourcing studies for each of these sites to see if finer chronological resolution may be attained.
One-mode network of sites connected to sites via similar proportions of raw material (just like thesis work).
One-mode with flipped node/edges so that strong similarities are nodes connected by sites represented as edges --- used to highlight sites as meeting points or borders à la Crumley and Marquadt 1988.
Two-mode network (two "classes" of nodes: sites and obsidian sources), with sites connected to sources (must figure out a weighting mechanism), and its one-mode derivative whereby sources are connected to other sources via sites who use each's material --- this latter networks used to determine groups of sources that are commonly used together.
The different ways in which these materials were used can then be added to discussion, and visualized accordingly by colourizing certain edges to highlight what kind of interactions they may represent, or to denote relationships among sites based upon other forms of evidence like pottery variation, use of seal stamps, etc.
Final map would look something like those drawn up by Delerue (2007) in her dissertation, but hopefully relating more to inter-relationships between sites, rather than between sites and sources.

#### Comments.
**Andy:**
Hi Zack,
A couple of quick thoughts:
Instead of "What are Joyce and Pauketat thinking? How does this relate to space, place and political economy?" I would suggest you consider a questions like, "How might a practice-based approach help with thinking about the emergence of new political and economic systems?"
This is because it may push you to read a bit more broadly on what this approach is about --- you may want to look, for instance, at a very famous article by Sherry Ortner "theory in anthropology since the sixties" which includes a section on theories of practice.
You have lots of data included here.
This paper should be no longer than 25 pages...
plan accordingly.
