---
title: Communicating social theory
date: 2014-10-06
draft: false
---

While discussing Tim Ingold's work in class today, and going over the ways that he conveys his ideas, I began to think about how we construct and communicate an understanding of the world around us as social scientists.
The use of analogy is really interesting because comparative examples get points across very effectively.
Also, there is a tendency for social theories to be commonly structured in terms of dialectical relationships or dualities, which suggest an opposition between two forces, a common structure in myth-making.
I'm left wondering whether similar comparisons between social theory and mythology can be made.

Incidentally, I recently re-watched one of my favourite episodes of Star Trek for the gazillionth time, _Darmok_.
In this episode, the Enterprise encounters representatives of the Children of Tama, or the Tamarians, a society that has puzzled the federation for generations due to their seemingly incomprehensible language.
Their language primarily consists of many proper nouns and grand actions, however without understanding the meaning behind these names and the situations behind the actions mentioned, it is impossible to fully comprehend what is being communicated.
As is implied throughout the episode, these recurrent words refer to scenes from mythology, and the Tamarians communicate via analogy to these commonly understood ideas.

It was only through re-creation of elements in these stories that Picard was able to understand anything that Dathon, the Tamarian captain, was trying to communicate.
They beam down to an isolated planet, where Dathon hands Picard a knife.
Picard totally misunderstood this gesture as an invitation to duel, but later on he opened his mind a bit when he began to notice various other gestures contradicting this assumption.
Moreover, Picard realizes that there is hope to understand the language, and that understanding it may in fact lead to positive outcomes.
When Picard realized that they were in danger, that there was a problem that could be resolved through Dathon's proposed gesture, he was totally willing to play along in order to overcome the conflict.
Dathon was critically wounded in the fight, and as he lay dying, Picard had his amazing a-ha! moment when everything seemed to click, in a similar way as when a puzzling concept gets untangled in my own mind.
Finally, through his retelling of the Epic of Gilgamesh to Dathon, Picard develops a more complete understanding of how to communicate with him and the rest of the Tamarian people.
Through this, Picard realizes that his own life, and his already established way of doing things, were already influenced by the same ideas that make up the Tamarian language.
