---
title: "Space, Place and Landscape - Blog #3"
# subtitle: "Space, Time, Place: A Humanistic Frame"
date: 2014-09-26
draft: false
---

In the book chapter I read this week - Yi-Fu Tuan's _Space, Time, Place: A Humanistic Frame_ --- the author outlines how space, time and place are commonly conceptualized from a humanistic (= anthropological?) perspective.
He examines the nature of these these elements (for lack of a better term) at four scales (I'm unsure if "scale" is used in the same way we refer to it).
This chapter is divided into sub-sections encompassing discussion pertaining to each of these scales, which are labeled as follows:

1. time in mythic space;
2. Greek-Hebrew models of space, time and place;
3. time and experiential space; and
4. time and place.

**Time in mythic space:**
Tuan observes that mythic space occurs in three ways: cosmogonic, astronomic, and human.
The first kind refers to origin myths, the second to observations of natural phenomena, and the third to human experiences.
While the author notes that cosmogonic and human space tend to be expressed in terms of linear development (a progression from beginning to end), astronomic space is more rhythmic or cyclical in nature.
Tuan then outlines various conceptualizations of mythic space through ethnographic examples in order to illustrate how these conceptions are actually put into practice.

**Space, time, place: Greek-Hebrew models:**
Tuan then goes over two case studies wherein he outlines supposed conceptualizations of space pertaining to Greek and Hebrew societies.
However I found this section extremely problematic in a couple ways.
First, the author did not draw upon enough primary sources derived from classical texts and archaeological evidence in order to derive his arguments in a convincing way (at least to me, a former classics student).
Am I to assume that Tuan's reference to Pericles' speeches, without pointing to specific notions that this Athenian politician may have presented, are representative of Athenian --- let alone pan-Hellenic --- attitudes?
Tuan also generalizes the group of people he refers to as Hebrews, who probably had very distinctive conceptualizations of space, time and place at different points in time (pre- and post-diaspora, for instance).
However as I read this while sitting with family who came together from many places to celebrate the Jewish new year, I do recognize some truth in Tuan's representation of Jewish (or Hebrew) tendencies to "build in time" and "temporalize" the structures they build (p. 10).
But this should not be compartmentalized as a Jewish phenomenon, and may also potentially be observed in other groups exhibiting similar histories and community structures.

I also believe that Tuan used this section to construct a notion of "western" conceptions of space, time and place.
I only bring this up because we discussed this in earlier blog comments and in class, and I don't want to open that can of worms again, but the idea that early Medieval models of the universe were derived as a synthesis of Greek and Hebrew conceptualizations seems overly simplistic to me.
Although additional arguments against this notion can likely be made, it is easiest to point out the considerable temporal gaps between Classical Greece (5th century BCE), 1st century AD Judaism/Christianity, and the Early Middle Ages (c. 400 - 1000 AD).

**Time and experiential space:**
This section describes how space is used to convey notions of time, and vice versa.
Tuan prompts discussion by referencing many common colloquial phrases, and the implied meanings behind them, that refer to time in spatial terms.
However I find that some of Tuan's interpretations crossover with ideas he presents in his first section dealing with mythic representations of space.
Now perhaps I'm confusing apples and oranges here, but I felt that the author's example of his drive to and from work at dawn and dusk complicates the notion he presents earlier that human space is conceptualized in linear terms.
A purely linear perspective of time supports an intentional aspect to agency, with each person reading their own path --- however the social structure in which we live brings habit into our lives, such as the cycle of driving to and from work at specific points in the day.
Although Tuan only wrote this book chapter around a year after Giddens' canonical work was published, I do think that perspectives of time play into ideas of agency and structure and should be explored more thoroughly in this light.
I also think that this must tie in to the different wavelengths of history presented by Braudel and other members of the Annales School, but to be honest I am not entirely sure how they explicitly relate.
Perhaps this will be discussed in more detail next class, and the relationship between structuration theory and the annales school will be made more clear.

Moreover, in this section Tuan explains how contemplation influences our perceptions of distance and extent of time.
After reading his quote, "Objects, space and time also become visible --- no longer the mere coordinates for habitual behaviours --- when they are contemplated" (p. 12-13), I am unsure about whether this refers to empirical measurement or critical thought.
From the tone of the article the latter is implied, however for some reason this brings to mind Heisenberg's uncertainty principle (which dictates that an object or entity whose properties are measured is altered through the act of physical observation, and is thus not in its natural or pristine state that it takes when unobserved), which is more concerned with the observation of physical things.
Are the conceptual and physical dictated by the same laws or guidelines?
Perhaps this question would be better addressed to humanists or philosophers.

**Time and place:**
I find that this section was more cryptic than the rest.
There were some short phrases that seemed out out place or without context, assuming that the reader would be able to come up with the implied meaning.
I do think that Tuan's idea of place as a static state is problematic.
If I remember a family trip to Maine one summer, and recall the places where I was (the town where I was staying, the house we rented, the beach, the car ride there and back, etc), I will not remember them in static ways.
Instead I will remember the experiences I had with my family, which were dynamic and occurred over the course of a few weeks.
The multiplicity of times and places, which transcend scales, are far from being "one relation between time and space" (Tuan's definition of place, p. 14).
Although I could not really understand the main point Tuan was trying to make in this section, I do disagree with this fundamental notion that he brings up.

**Overall synthesis:**
This was an interesting and fun read, however I think that it was too brief for the broad scope of ideas covered.
Although I have not yet read his other work, Yi-Fu Tuan, who is credited by many as the founder of human geography, has written extensively on the relationship between space, time and place, so perhaps the criticism I made is not warranted in the larger scope of his work.
However I think that this particular book chapter would have been more informative if these sections were broken up into their own dedicated works, with more elaborate discussion dedicated to the ideas presented by others whom Tuan references.

#### Comments
**Alex:**
I felt the same way as you Zack when I was reading this chapter.
I was underwhelmed by what I thought was a lack of sources or groundwork in Tuan's essay.
Specifically, in the section "Time and Experiential Space" I was intrigued by how Tuan considered the effect contemplation has on our experience of distance and time.
This is a point I hope to bring up in class with regards to Heidegger, as I think his argument is much stronger whereas Tuan seemed to lack the "philosophical rigour" I have come to expect in such discussions.
The essay did feel almost like an introduction to a book, which makes me wonder like you whether our criticisms would be answered further in the project.

**Mary:**
Zack I liked your critique of Tuan's generalization of his Greek and Hebrew societies.
I felt that his examples were over simplified versions of reality but they did fit neatly into his narrative and nicely illustrated the difficult concepts he was explaining.

Maybe Alex is right and this chapter didn't insight the 'philosophical rigor' that is usually associated with these kinds of discussions but I felt that it was written to allow an entry point for people to start understanding time and space in a new way.
People, like me, who feel they are playing catch-up with experience in such theoretical and philosophical conversations, will greatly appreciate Tuan's approach.

**Sean:**
Zack, in response to your "humanistic = anthropological" question mark at the beginning.
I think that at this point (in 1978) usage of the term "humanistic" in the field of geography was largely equated with an approach that considers "human agency" as central to their study; or in other words, they considered the value and/or visibility of the "decisions and dispositions" of humans in the archaeological record.
I could be wrong, but when Tuan says "humanism" I think he just means that he is thinking in terms of how humans conceptualize and interact with the "space, time and place" that surrounds them, which I think is pretty respectable considering it was written almost four decades ago.

In terms of the article, I actually quite enjoyed it.
Overall, I would have to agree with Mary here.
It might not have been couched in the philosophical traditions that would now be required of such an investigation of these principles, but it does allow for an effective method of understanding and appreciating these issues.

You are certainly right to question the author's temporal variability in his choice of case studies, but I don't think the discrepancies are problematic in this situation.
If he was using these as comparative examples in any attempt to prove their relation to each other, it probably would have been a bad move.
But I think he used them as examples to illuminate how many ways human perspectives have manifested themselves in the minds and societies that have existed over time.

At the end, Tuan accuses the field of human geography of largely ignoring "time as a dimension of human experience" (16).
Ultimately, he is proposing that the field of geography begin really considering these experiences of humanity in order to infuse a sense of reality into the geographer's world.
In this way, it is not meant as a philosophical or even anthropological piece (in terms of who the primary audience was expected to be), so we might be able to forgive him for not being so thorough in his philosophical underpinnings.

And finally, as Alex mentioned, this article is situated at the very beginning of a good sized book entitled "Making Sense of Time", so perhaps this chapter was not intended to entirely justify the humanistic approach, but merely to approach these topics and set the stage for further discussion later on.
I, for one, don't really feel like reading the rest of the book just to find out though...

**Zack:**
Okay, it seems that I've been a bit too not-picky here, and after re-reading it I do see this as a useful introductory piece that gets us into the idea of what phenemenology can be about.
It seems like an odd fit in relation to other readings in the syllabus, but figuring out the intended audience really clarified its value to me.

**Andy:**
Hey Zack, thanks for the overview --- we will definitely dig into this some more tomorrow.
I wonder if you or anybody else can you perhaps see what Tuan is bringing to the table that the other phenomenology we read this week aren't?
BTW, Sean is basically right on this --- although more specifically the use of "humanist" is referring specifically to how geographers studied space previously, which was empirically-rich but fairly abstract and certainly not focused on the "experienced".
