---
title: "Space, Place and Landscape - Blog #2"
# subtitle: Unintended Consequences? Monumentality as a Novel Experience in Formative Mesoamerica by R. Joyce, 2004
date: 2014-09-21
draft: false
---

This week I was assigned to blog about the article written by Joyce, _Unintended Consequences? Monumentality as a Novel Experience in Formative Mesoamerica_, which reevaluates the circumstances that may have led to the construction of monuments during the Formative Period in Mesoamerica.
Joyce illustrates how the first clay platforms were constructed using knowledge from prior experience working with the same materials, and speculates on how they were perceived by those who lived alongside them when they were first built. She dismisses the idea that monuments were built for their own sake, and instead proposes that the notable platforms were the result of normal practices used when constructing houses upon the site of a preceding structure.
The larger surface area in which the clay was laid out resulted in extended longevity for the structure and social differentiation for people associated with it via phenomenological control and access restrictions.

Joyce draws on the work of @giddens1977 in order to highlight the role of already existing structure and practices in shaping new socio-political developments.
The author guides us through a scenario in which an actor would initiate the construction of a grand monument in an explicitly intentional manner, which is shown to be not that realistic.
Instead, Joyce proposes that the permanence of these platforms results from similar practices as before, albeit performed under different circumstances, namely the application of clay onto a wider and flatter surface.
This means that the mobilization of labour would have likely occurred within the already-existing social structure featuring already-existing practices.

However what if the social structure of the status quo (prior to "monumental" platforms) was already of a manner that would have favoured socio-political control or the restriction of specialized knowledge?
Although the readings this week emphasized the relationships between place and power, at times I felt that place was given too much attention as a way of solidifying control.
Monuments and control of special places are useful in that regard, however what about the role of clothing, jewelry, or other alienable or inalienable possessions?
And what about restricted knowledge or practices?
If some form of social influence was already in effect then the unlikely scenario posed by Joyce, in which an actor somehow convinces her community to drop everything and build a monument, may contain some credibility after all.
However a solid rebuttal to this counter-argument is that these things may all be associated with certain places (i.e. raw materials come from a certain place; knowledge is often inspired by nature, which occurs at a place), and that social differentiation is derived from control over the thing's use, which may be best accomplished through control of the places from which the things may be derived.
So it seems that I've come full circle (... I think) and ultimately I'm a bit confused after writing out this post.
Maybe after thinking about this some more, and reading some of the comments, I'll update with further thoughts.

**UPDATE:**
Following Dr. Roddick's prompts, I re-read Joyce's article with more attention paid to the high theory involved.
The author clearly draws from Giddens' duality of structure and agency, a theoretical pillar that recognizes the roles of individual agents in the reproduction and transformation of social structure that in turn feedbacks into the actions of individuals.
At the core of Giddens' work is his appreciation of the role of individual human agents in shaping social structure through persistence or repetition of certain cultural practices, rather than characterizing societies based on the institutions in place.
Giddens draws an analogy to languages to explain his ideas in a more relatable way; language is simply and effectively the encryption and decryption of information by parties with a mutual understanding of the meanings behind words and letters, and the "rules" for processing information are rather implicit to those communicating.
As with social structure, the rules of transferring information or ways of acting are implicit in our minds, however they are loosely defined based on the behaviour of others in the collective.
As people tend to view the world differently and interact in different ways, languages and social protocol shift as well.
The actions of and interactions between individuals thus shape the overall social structure, yet actors are concurrently influenced by this worldview that they shape.
The implicit nature of protocols that shape social structure suggests a degree of un-inentionality in the actions of agents, an issue that came up when characterizing agency in class, albeit briefly in preparation for a more in-depth discussion later on.

Joyce tied in structuration theory after recognizing that the construction of later monumental platforms could have been derived from practices already in place prior to the explicit intention of building monuments.
The phenomenological changes that arose from the construction of certain larger platforms would have occurred unintentionally, rather than as a result of intentional motivations to build a monument.
While I don't claim to have any  knowledge regarding phenomenology, I think that the cognitive changes that drove these societal shifts need to be made more explicit, and that discussion on transformation itself remains the weakest link in Joyce's argument.
Although the author does refer to Love's work (published a 1999 volume co-edited by Joyce), I have not had the chance to read this yet.

Joyce recognizes that social structure is a product of individuals' actions, and that peoples' actions --- which are often unintentionally driven --- are the result of social pressures.
At the surface this seems kind of cyclical, but it does seem to make sense.
I just feel that we need to be able to map the processes involved in these transformations better, and perhaps formalize the way that Giddens' structuration theory is applied.

**About Rosemary Joyce:**
Rosemary Joyce is an anthropological archaeologist at UC Berkeley, and is a leading figure in the field of social archaeology.
Her work focuses on ceramic analysis, household archaeology, and the archaeology of sex and gender, but these interests seem to stem out into other related fields as well.
Joyce has a blog, [Ancient Bodies, Ancient Lives](https://ancientbodies.wordpress.com/), where she reflects on perceptions of sex and gender of the past as portrayed in contemporary media and archaeology news reports, providing a more informed perspective for the general public in amazingly accessible language and format.


#### Comments
**Andy:**
Hi Zack, Maybe I can make a suggestion here?
Perhaps you (and with the help of others) can dig into the key "big question" of the article, the high theory if you will, which revolves around the idea of structuration vis-a-vis bigger debates around structure: agency.
Perhaps give us a bit more on structuration.
Of course we briefly introduced the notion of agency last week.
Perhaps we can work towards the nitty gritty of Gidden's idea, and how Joyce is using this to help understand agency and structure in the context of early sites in Mesoamerica.
What is Joyce's view on those troubling issues of "intention" and agency as individuals, which we also discussed last week in our introduction to agency.
Then turn to think through the how this is explored in the archaeological data.
In other words, go from the "high theory" to the nuts and bolts of the case study.

**Alex:**
After reading your update, I felt like I had a better grasp of the way Joyce links the theoretical idea of structuration and agency to the example of monumentality in Formative Mesoamerica.
Specifically, I liked your comment that "the cognitive changes that drove these societal shifts need to be made more explicit, and that discussion on transformation itself remains the weakest link in Joyce's argument."
Though I understand your point that such a link presents a weakness in Joyce's argument, I think we could give her more credit.
Taken as a hypothetical, Joyce's claim that early "monumental" platforms caused a phenomenological shift through unintended consequences can be useful to us as a mode of investigation.

Let me try to be a little more clear.
I think that the strongest aspect of Joyce's essay was her refusal to accept explanations for early monumental platforms based in our contemporary perception of monumentality today.
Instead, by focusing on the unintended consequences of building these platforms, she forces us to rethink the beginnings of monumentality outside of a presentist view.
I find such an investigative strategy intellectually courageous and admirable.
And despite the empirical strength of her claim, I feel her strategy alone is significant.

**Andy:**
Very nicely put.
Another way to say it, is that Joyce is concerned with "looking up" through time, rather than looking back.
Many explanations for transformations are based heavily upon what emerged.
In contrast, Joyce is interested in thinking through the materials, and previous experiences with those materials (in this case, clay), and the potential ripple effect they may have had.
For instance, "new concept of architecture as something potentially more permanent may have shifted the way that residential structures were assessed, placing a greater value on permanency in those as well.
At Puerto Escondido, for example, the use of lime plaster and stone facings becomes a feature of monumental earthen and of residential architecture simultaneously, with the earliest plastered platforms platforms dating to 1100-900 B.C.
Prior to that point, our construction evidence suggests buildings with post frameworks supported perishable superstructures, and these buildings were remodeled many times in succession." (p. 19).
We can actually think of architecture that's still with us today in a similar fashion.
For instance, does anyone know the story behind front porches in North America?

**Andy:**
...and thanks Zack for the update --- we'll definitely explore this in more detail tomorrow!
