---
title: Github for archaeological databases
date: 2014-08-03
categories:
  - archaeological research
  - multidisciplinarity
  - archaeological data
draft: false
---

Today I submitted an abstract for a poster presentation at the AIA Annual Meeting in January on the [Database of Obsidian Sourcing Studies (DObsiSS)](http://zackbatist.github.io/DObsiSS/), a compilation of obsidian sourcing results pertaining to Neolithic contexts in southwest Asia and Anatolia.
I made this database for my M.A. thesis, which utilizes network analysis in order to assess and re-conceptualize Neolithization and regional interaction in this setting.
I recently made DObsiSS available on Github, so anyone can access the data or commit modifications. Although Github (and the git protocol at its core) is primarily a code-sharing platform, it's seen some great applications in the realm of [academic writing](http://chronicle.com/blogs/profhacker/tag/github101) and [scientific database management](http://blog.okfn.org/2013/07/02/git-and-github-for-data/).
A great introduction to git for scientists and academics is available [here](http://nyuccl.org/pages/GitTutorial/), and a more practical guide can be found [here](http://rogerdudler.github.io/git-guide/).

I think that there is a lot of potential for the use of git to manage archaeological databases.
It enables data sharing and re-use, encourages collaboration and communication among members of the community, makes work more transparent, and breaks down the common notion that archaeological databases exist in isolation or can ever be "complete".
Interestingly, the antithesis to these concerns seem to be the thorniest issues in archaeological data management.

---

**The Database of Obsidian Sourcing Studies (DObsiSS): Using Git for Collaborative Management of Archaeological Data**\
The Database of Obsidian Sourcing Studies (DObsiSS) is an integrated listing of chemically characterized archaeological obsidian compiled from published journal articles, excavation reports, conference papers and other scholarly records.
Obsidian is a volcanic glass that was used throughout prehistory to produce razor sharp cutting tools, and it has chemical properties that enable archaeologists to identify the source from which the raw material derives.
This information is used to determine whether the inhabitants of a site participated in large-scale exchange networks, as well as the capacity of their involvement.
Although a large amount of data has been generated over the years, obsidian sourcing studies tend to be done independently, with results published in journals aimed towards specialized researchers, detailed in regional-journal field reports, or kept as supplementary material in databases held by archaeometric laboratories.
Aside from the issue of data accessibility, the redundancy of published results and a lack of standardization among laboratories complicate efforts to compare and analyze all of this information.
The database presented here is the result of an effort to make this immense wealth of data more useful for archaeologists or for academics of other disciplines.

DObsiSS is an open access online resource that is continuously updated to include newly published data.
The database operates using git --– a collaborative data sharing protocol that allows anyone to commit proposals for modification, submit new content to be added, and track any changes in a transparent manner.
It is also a great platform for discussion, where anyone may enquire about particular proposed modifications or make suggestions for larger improvements.
This effort to compile all obsidian sourcing data into a central repository is a great use case for archaeological applications of git, which was designed so that content may be easily expanded, to encourage greater collaboration among researchers, and to enable fact checking and error reporting from knowledgeable members of the community.
This poster presentation outlines the implementation of git as it pertains to DObsiSS, and highlights the potential benefits of its wider adoption by archaeologists.



